spring:
  profiles:
    active: db,admin,core
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  ERROR
#static:
#  upload:
#    path: e:/img/
#  server:
#    address: http://localhost:8777/