package com.yjh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class AllGysExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public AllGysExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public AllGysExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public AllGysExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllGysExample example = new AllGysExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public AllGysExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public AllGysExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGysbmIsNull() {
            addCriterion("gysbm is null");
            return (Criteria) this;
        }

        public Criteria andGysbmIsNotNull() {
            addCriterion("gysbm is not null");
            return (Criteria) this;
        }

        public Criteria andGysbmEqualTo(String value) {
            addCriterion("gysbm =", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmNotEqualTo(String value) {
            addCriterion("gysbm <>", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmGreaterThan(String value) {
            addCriterion("gysbm >", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmGreaterThanOrEqualTo(String value) {
            addCriterion("gysbm >=", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmLessThan(String value) {
            addCriterion("gysbm <", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmLessThanOrEqualTo(String value) {
            addCriterion("gysbm <=", value, "gysbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysbmLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysbmLike(String value) {
            addCriterion("gysbm like", value, "gysbm");
            return (Criteria) this;
        }

        public Criteria andGysbmNotLike(String value) {
            addCriterion("gysbm not like", value, "gysbm");
            return (Criteria) this;
        }

        public Criteria andGysbmIn(List<String> values) {
            addCriterion("gysbm in", values, "gysbm");
            return (Criteria) this;
        }

        public Criteria andGysbmNotIn(List<String> values) {
            addCriterion("gysbm not in", values, "gysbm");
            return (Criteria) this;
        }

        public Criteria andGysbmBetween(String value1, String value2) {
            addCriterion("gysbm between", value1, value2, "gysbm");
            return (Criteria) this;
        }

        public Criteria andGysbmNotBetween(String value1, String value2) {
            addCriterion("gysbm not between", value1, value2, "gysbm");
            return (Criteria) this;
        }

        public Criteria andYwqybmIsNull() {
            addCriterion("ywqybm is null");
            return (Criteria) this;
        }

        public Criteria andYwqybmIsNotNull() {
            addCriterion("ywqybm is not null");
            return (Criteria) this;
        }

        public Criteria andYwqybmEqualTo(Integer value) {
            addCriterion("ywqybm =", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmNotEqualTo(Integer value) {
            addCriterion("ywqybm <>", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmGreaterThan(Integer value) {
            addCriterion("ywqybm >", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmGreaterThanOrEqualTo(Integer value) {
            addCriterion("ywqybm >=", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmLessThan(Integer value) {
            addCriterion("ywqybm <", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmLessThanOrEqualTo(Integer value) {
            addCriterion("ywqybm <=", value, "ywqybm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andYwqybmLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ywqybm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYwqybmIn(List<Integer> values) {
            addCriterion("ywqybm in", values, "ywqybm");
            return (Criteria) this;
        }

        public Criteria andYwqybmNotIn(List<Integer> values) {
            addCriterion("ywqybm not in", values, "ywqybm");
            return (Criteria) this;
        }

        public Criteria andYwqybmBetween(Integer value1, Integer value2) {
            addCriterion("ywqybm between", value1, value2, "ywqybm");
            return (Criteria) this;
        }

        public Criteria andYwqybmNotBetween(Integer value1, Integer value2) {
            addCriterion("ywqybm not between", value1, value2, "ywqybm");
            return (Criteria) this;
        }

        public Criteria andGysmcIsNull() {
            addCriterion("gysmc is null");
            return (Criteria) this;
        }

        public Criteria andGysmcIsNotNull() {
            addCriterion("gysmc is not null");
            return (Criteria) this;
        }

        public Criteria andGysmcEqualTo(String value) {
            addCriterion("gysmc =", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcNotEqualTo(String value) {
            addCriterion("gysmc <>", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcGreaterThan(String value) {
            addCriterion("gysmc >", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcGreaterThanOrEqualTo(String value) {
            addCriterion("gysmc >=", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcLessThan(String value) {
            addCriterion("gysmc <", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcLessThanOrEqualTo(String value) {
            addCriterion("gysmc <=", value, "gysmc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysmcLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysmc <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysmcLike(String value) {
            addCriterion("gysmc like", value, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGysmcNotLike(String value) {
            addCriterion("gysmc not like", value, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGysmcIn(List<String> values) {
            addCriterion("gysmc in", values, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGysmcNotIn(List<String> values) {
            addCriterion("gysmc not in", values, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGysmcBetween(String value1, String value2) {
            addCriterion("gysmc between", value1, value2, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGysmcNotBetween(String value1, String value2) {
            addCriterion("gysmc not between", value1, value2, "gysmc");
            return (Criteria) this;
        }

        public Criteria andGyshybhIsNull() {
            addCriterion("gyshybh is null");
            return (Criteria) this;
        }

        public Criteria andGyshybhIsNotNull() {
            addCriterion("gyshybh is not null");
            return (Criteria) this;
        }

        public Criteria andGyshybhEqualTo(String value) {
            addCriterion("gyshybh =", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhNotEqualTo(String value) {
            addCriterion("gyshybh <>", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhGreaterThan(String value) {
            addCriterion("gyshybh >", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhGreaterThanOrEqualTo(String value) {
            addCriterion("gyshybh >=", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhLessThan(String value) {
            addCriterion("gyshybh <", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhLessThanOrEqualTo(String value) {
            addCriterion("gyshybh <=", value, "gyshybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGyshybhLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gyshybh <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGyshybhLike(String value) {
            addCriterion("gyshybh like", value, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andGyshybhNotLike(String value) {
            addCriterion("gyshybh not like", value, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andGyshybhIn(List<String> values) {
            addCriterion("gyshybh in", values, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andGyshybhNotIn(List<String> values) {
            addCriterion("gyshybh not in", values, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andGyshybhBetween(String value1, String value2) {
            addCriterion("gyshybh between", value1, value2, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andGyshybhNotBetween(String value1, String value2) {
            addCriterion("gyshybh not between", value1, value2, "gyshybh");
            return (Criteria) this;
        }

        public Criteria andLxrIsNull() {
            addCriterion("lxr is null");
            return (Criteria) this;
        }

        public Criteria andLxrIsNotNull() {
            addCriterion("lxr is not null");
            return (Criteria) this;
        }

        public Criteria andLxrEqualTo(String value) {
            addCriterion("lxr =", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrNotEqualTo(String value) {
            addCriterion("lxr <>", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrGreaterThan(String value) {
            addCriterion("lxr >", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrGreaterThanOrEqualTo(String value) {
            addCriterion("lxr >=", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrLessThan(String value) {
            addCriterion("lxr <", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrLessThanOrEqualTo(String value) {
            addCriterion("lxr <=", value, "lxr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxrLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxrLike(String value) {
            addCriterion("lxr like", value, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxrNotLike(String value) {
            addCriterion("lxr not like", value, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxrIn(List<String> values) {
            addCriterion("lxr in", values, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxrNotIn(List<String> values) {
            addCriterion("lxr not in", values, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxrBetween(String value1, String value2) {
            addCriterion("lxr between", value1, value2, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxrNotBetween(String value1, String value2) {
            addCriterion("lxr not between", value1, value2, "lxr");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNull() {
            addCriterion("lxdh is null");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNotNull() {
            addCriterion("lxdh is not null");
            return (Criteria) this;
        }

        public Criteria andLxdhEqualTo(String value) {
            addCriterion("lxdh =", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhNotEqualTo(String value) {
            addCriterion("lxdh <>", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThan(String value) {
            addCriterion("lxdh >", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThanOrEqualTo(String value) {
            addCriterion("lxdh >=", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhLessThan(String value) {
            addCriterion("lxdh <", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhLessThanOrEqualTo(String value) {
            addCriterion("lxdh <=", value, "lxdh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andLxdhLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("lxdh <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLxdhLike(String value) {
            addCriterion("lxdh like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotLike(String value) {
            addCriterion("lxdh not like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhIn(List<String> values) {
            addCriterion("lxdh in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotIn(List<String> values) {
            addCriterion("lxdh not in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhBetween(String value1, String value2) {
            addCriterion("lxdh between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotBetween(String value1, String value2) {
            addCriterion("lxdh not between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andGysjjIsNull() {
            addCriterion("gysjj is null");
            return (Criteria) this;
        }

        public Criteria andGysjjIsNotNull() {
            addCriterion("gysjj is not null");
            return (Criteria) this;
        }

        public Criteria andGysjjEqualTo(String value) {
            addCriterion("gysjj =", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjNotEqualTo(String value) {
            addCriterion("gysjj <>", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjGreaterThan(String value) {
            addCriterion("gysjj >", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjGreaterThanOrEqualTo(String value) {
            addCriterion("gysjj >=", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjLessThan(String value) {
            addCriterion("gysjj <", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjLessThanOrEqualTo(String value) {
            addCriterion("gysjj <=", value, "gysjj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andGysjjLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("gysjj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGysjjLike(String value) {
            addCriterion("gysjj like", value, "gysjj");
            return (Criteria) this;
        }

        public Criteria andGysjjNotLike(String value) {
            addCriterion("gysjj not like", value, "gysjj");
            return (Criteria) this;
        }

        public Criteria andGysjjIn(List<String> values) {
            addCriterion("gysjj in", values, "gysjj");
            return (Criteria) this;
        }

        public Criteria andGysjjNotIn(List<String> values) {
            addCriterion("gysjj not in", values, "gysjj");
            return (Criteria) this;
        }

        public Criteria andGysjjBetween(String value1, String value2) {
            addCriterion("gysjj between", value1, value2, "gysjj");
            return (Criteria) this;
        }

        public Criteria andGysjjNotBetween(String value1, String value2) {
            addCriterion("gysjj not between", value1, value2, "gysjj");
            return (Criteria) this;
        }

        public Criteria andSsywyIsNull() {
            addCriterion("ssywy is null");
            return (Criteria) this;
        }

        public Criteria andSsywyIsNotNull() {
            addCriterion("ssywy is not null");
            return (Criteria) this;
        }

        public Criteria andSsywyEqualTo(String value) {
            addCriterion("ssywy =", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyNotEqualTo(String value) {
            addCriterion("ssywy <>", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyGreaterThan(String value) {
            addCriterion("ssywy >", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyGreaterThanOrEqualTo(String value) {
            addCriterion("ssywy >=", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyLessThan(String value) {
            addCriterion("ssywy <", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyLessThanOrEqualTo(String value) {
            addCriterion("ssywy <=", value, "ssywy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andSsywyLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("ssywy <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsywyLike(String value) {
            addCriterion("ssywy like", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotLike(String value) {
            addCriterion("ssywy not like", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyIn(List<String> values) {
            addCriterion("ssywy in", values, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotIn(List<String> values) {
            addCriterion("ssywy not in", values, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyBetween(String value1, String value2) {
            addCriterion("ssywy between", value1, value2, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotBetween(String value1, String value2) {
            addCriterion("ssywy not between", value1, value2, "ssywy");
            return (Criteria) this;
        }

        public Criteria andTjrIsNull() {
            addCriterion("tjr is null");
            return (Criteria) this;
        }

        public Criteria andTjrIsNotNull() {
            addCriterion("tjr is not null");
            return (Criteria) this;
        }

        public Criteria andTjrEqualTo(String value) {
            addCriterion("tjr =", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrNotEqualTo(String value) {
            addCriterion("tjr <>", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrGreaterThan(String value) {
            addCriterion("tjr >", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrGreaterThanOrEqualTo(String value) {
            addCriterion("tjr >=", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLessThan(String value) {
            addCriterion("tjr <", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLessThanOrEqualTo(String value) {
            addCriterion("tjr <=", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjrLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLike(String value) {
            addCriterion("tjr like", value, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotLike(String value) {
            addCriterion("tjr not like", value, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrIn(List<String> values) {
            addCriterion("tjr in", values, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotIn(List<String> values) {
            addCriterion("tjr not in", values, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrBetween(String value1, String value2) {
            addCriterion("tjr between", value1, value2, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotBetween(String value1, String value2) {
            addCriterion("tjr not between", value1, value2, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjsjIsNull() {
            addCriterion("tjsj is null");
            return (Criteria) this;
        }

        public Criteria andTjsjIsNotNull() {
            addCriterion("tjsj is not null");
            return (Criteria) this;
        }

        public Criteria andTjsjEqualTo(LocalDateTime value) {
            addCriterion("tjsj =", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjNotEqualTo(LocalDateTime value) {
            addCriterion("tjsj <>", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjGreaterThan(LocalDateTime value) {
            addCriterion("tjsj >", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tjsj >=", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjLessThan(LocalDateTime value) {
            addCriterion("tjsj <", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tjsj <=", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andTjsjLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("tjsj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjIn(List<LocalDateTime> values) {
            addCriterion("tjsj in", values, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjNotIn(List<LocalDateTime> values) {
            addCriterion("tjsj not in", values, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tjsj between", value1, value2, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tjsj not between", value1, value2, "tjsj");
            return (Criteria) this;
        }

        public Criteria andZhxgrIsNull() {
            addCriterion("zhxgr is null");
            return (Criteria) this;
        }

        public Criteria andZhxgrIsNotNull() {
            addCriterion("zhxgr is not null");
            return (Criteria) this;
        }

        public Criteria andZhxgrEqualTo(String value) {
            addCriterion("zhxgr =", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrNotEqualTo(String value) {
            addCriterion("zhxgr <>", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrGreaterThan(String value) {
            addCriterion("zhxgr >", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrGreaterThanOrEqualTo(String value) {
            addCriterion("zhxgr >=", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLessThan(String value) {
            addCriterion("zhxgr <", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLessThanOrEqualTo(String value) {
            addCriterion("zhxgr <=", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgrLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLike(String value) {
            addCriterion("zhxgr like", value, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotLike(String value) {
            addCriterion("zhxgr not like", value, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrIn(List<String> values) {
            addCriterion("zhxgr in", values, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotIn(List<String> values) {
            addCriterion("zhxgr not in", values, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrBetween(String value1, String value2) {
            addCriterion("zhxgr between", value1, value2, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotBetween(String value1, String value2) {
            addCriterion("zhxgr not between", value1, value2, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgsjIsNull() {
            addCriterion("zhxgsj is null");
            return (Criteria) this;
        }

        public Criteria andZhxgsjIsNotNull() {
            addCriterion("zhxgsj is not null");
            return (Criteria) this;
        }

        public Criteria andZhxgsjEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj =", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj <>", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjGreaterThan(LocalDateTime value) {
            addCriterion("zhxgsj >", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj >=", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjLessThan(LocalDateTime value) {
            addCriterion("zhxgsj <", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj <=", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("zhxgsj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjIn(List<LocalDateTime> values) {
            addCriterion("zhxgsj in", values, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotIn(List<LocalDateTime> values) {
            addCriterion("zhxgsj not in", values, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("zhxgsj between", value1, value2, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("zhxgsj not between", value1, value2, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzNotEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanOrEqualToColumn(AllGys.Column column) {
            addCriterion(new StringBuilder("bz <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_gys
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private AllGysExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        protected Criteria(AllGysExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public AllGysExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_gys
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllGysExample example);
    }
}