package com.yjh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class AllGys {

    public AllGys() {

    }

    public AllGys(String gysbm, Integer ywqybm, String gysmc, String gyshybh,
                  String lxr, String lxdh, String gysjj, String ssywy, String tjr,
                  LocalDateTime tjsj, String zhxgr, LocalDateTime zhxgsj, String bz) {
        this.gysbm = gysbm;
        this.ywqybm = ywqybm;
        this.gysmc = gysmc;
        this.gyshybh = gyshybh;
        this.lxr = lxr;
        this.lxdh = lxdh;
        this.gysjj = gysjj;
        this.ssywy = ssywy;
        this.tjr = tjr;
        this.tjsj = tjsj;
        this.zhxgr = zhxgr;
        this.zhxgsj = zhxgsj;
        this.bz = bz;

    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.gysbm
     *
     * @mbg.generated
     */
    private String gysbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.ywqybm
     *
     * @mbg.generated
     */
    private Integer ywqybm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.gysmc
     *
     * @mbg.generated
     */
    private String gysmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.gyshybh
     *
     * @mbg.generated
     */
    private String gyshybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.lxr
     *
     * @mbg.generated
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.lxdh
     *
     * @mbg.generated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.gysjj
     *
     * @mbg.generated
     */
    private String gysjj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.ssywy
     *
     * @mbg.generated
     */
    private String ssywy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.tjr
     *
     * @mbg.generated
     */
    private String tjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.tjsj
     *
     * @mbg.generated
     */
    private LocalDateTime tjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.zhxgr
     *
     * @mbg.generated
     */
    private String zhxgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.zhxgsj
     *
     * @mbg.generated
     */
    private LocalDateTime zhxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_gys.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.gysbm
     *
     * @return the value of all_gys.gysbm
     * @mbg.generated
     */
    public String getGysbm() {
        return gysbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.gysbm
     *
     * @param gysbm the value for all_gys.gysbm
     * @mbg.generated
     */
    public void setGysbm(String gysbm) {
        this.gysbm = gysbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.ywqybm
     *
     * @return the value of all_gys.ywqybm
     * @mbg.generated
     */
    public Integer getYwqybm() {
        return ywqybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.ywqybm
     *
     * @param ywqybm the value for all_gys.ywqybm
     * @mbg.generated
     */
    public void setYwqybm(Integer ywqybm) {
        this.ywqybm = ywqybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.gysmc
     *
     * @return the value of all_gys.gysmc
     * @mbg.generated
     */
    public String getGysmc() {
        return gysmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.gysmc
     *
     * @param gysmc the value for all_gys.gysmc
     * @mbg.generated
     */
    public void setGysmc(String gysmc) {
        this.gysmc = gysmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.gyshybh
     *
     * @return the value of all_gys.gyshybh
     * @mbg.generated
     */
    public String getGyshybh() {
        return gyshybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.gyshybh
     *
     * @param gyshybh the value for all_gys.gyshybh
     * @mbg.generated
     */
    public void setGyshybh(String gyshybh) {
        this.gyshybh = gyshybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.lxr
     *
     * @return the value of all_gys.lxr
     * @mbg.generated
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.lxr
     *
     * @param lxr the value for all_gys.lxr
     * @mbg.generated
     */
    public void setLxr(String lxr) {
        this.lxr = lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.lxdh
     *
     * @return the value of all_gys.lxdh
     * @mbg.generated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.lxdh
     *
     * @param lxdh the value for all_gys.lxdh
     * @mbg.generated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.gysjj
     *
     * @return the value of all_gys.gysjj
     * @mbg.generated
     */
    public String getGysjj() {
        return gysjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.gysjj
     *
     * @param gysjj the value for all_gys.gysjj
     * @mbg.generated
     */
    public void setGysjj(String gysjj) {
        this.gysjj = gysjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.ssywy
     *
     * @return the value of all_gys.ssywy
     * @mbg.generated
     */
    public String getSsywy() {
        return ssywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.ssywy
     *
     * @param ssywy the value for all_gys.ssywy
     * @mbg.generated
     */
    public void setSsywy(String ssywy) {
        this.ssywy = ssywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.tjr
     *
     * @return the value of all_gys.tjr
     * @mbg.generated
     */
    public String getTjr() {
        return tjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.tjr
     *
     * @param tjr the value for all_gys.tjr
     * @mbg.generated
     */
    public void setTjr(String tjr) {
        this.tjr = tjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.tjsj
     *
     * @return the value of all_gys.tjsj
     * @mbg.generated
     */
    public LocalDateTime getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.tjsj
     *
     * @param tjsj the value for all_gys.tjsj
     * @mbg.generated
     */
    public void setTjsj(LocalDateTime tjsj) {
        this.tjsj = tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.zhxgr
     *
     * @return the value of all_gys.zhxgr
     * @mbg.generated
     */
    public String getZhxgr() {
        return zhxgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.zhxgr
     *
     * @param zhxgr the value for all_gys.zhxgr
     * @mbg.generated
     */
    public void setZhxgr(String zhxgr) {
        this.zhxgr = zhxgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.zhxgsj
     *
     * @return the value of all_gys.zhxgsj
     * @mbg.generated
     */
    public LocalDateTime getZhxgsj() {
        return zhxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.zhxgsj
     *
     * @param zhxgsj the value for all_gys.zhxgsj
     * @mbg.generated
     */
    public void setZhxgsj(LocalDateTime zhxgsj) {
        this.zhxgsj = zhxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_gys.bz
     *
     * @return the value of all_gys.bz
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_gys.bz
     *
     * @param bz the value for all_gys.bz
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gysbm=").append(gysbm);
        sb.append(", ywqybm=").append(ywqybm);
        sb.append(", gysmc=").append(gysmc);
        sb.append(", gyshybh=").append(gyshybh);
        sb.append(", lxr=").append(lxr);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", gysjj=").append(gysjj);
        sb.append(", ssywy=").append(ssywy);
        sb.append(", tjr=").append(tjr);
        sb.append(", tjsj=").append(tjsj);
        sb.append(", zhxgr=").append(zhxgr);
        sb.append(", zhxgsj=").append(zhxgsj);
        sb.append(", bz=").append(bz);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AllGys other = (AllGys) that;
        return (this.getGysbm() == null ? other.getGysbm() == null : this.getGysbm().equals(other.getGysbm()))
                && (this.getYwqybm() == null ? other.getYwqybm() == null : this.getYwqybm().equals(other.getYwqybm()))
                && (this.getGysmc() == null ? other.getGysmc() == null : this.getGysmc().equals(other.getGysmc()))
                && (this.getGyshybh() == null ? other.getGyshybh() == null : this.getGyshybh().equals(other.getGyshybh()))
                && (this.getLxr() == null ? other.getLxr() == null : this.getLxr().equals(other.getLxr()))
                && (this.getLxdh() == null ? other.getLxdh() == null : this.getLxdh().equals(other.getLxdh()))
                && (this.getGysjj() == null ? other.getGysjj() == null : this.getGysjj().equals(other.getGysjj()))
                && (this.getSsywy() == null ? other.getSsywy() == null : this.getSsywy().equals(other.getSsywy()))
                && (this.getTjr() == null ? other.getTjr() == null : this.getTjr().equals(other.getTjr()))
                && (this.getTjsj() == null ? other.getTjsj() == null : this.getTjsj().equals(other.getTjsj()))
                && (this.getZhxgr() == null ? other.getZhxgr() == null : this.getZhxgr().equals(other.getZhxgr()))
                && (this.getZhxgsj() == null ? other.getZhxgsj() == null : this.getZhxgsj().equals(other.getZhxgsj()))
                && (this.getBz() == null ? other.getBz() == null : this.getBz().equals(other.getBz()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGysbm() == null) ? 0 : getGysbm().hashCode());
        result = prime * result + ((getYwqybm() == null) ? 0 : getYwqybm().hashCode());
        result = prime * result + ((getGysmc() == null) ? 0 : getGysmc().hashCode());
        result = prime * result + ((getGyshybh() == null) ? 0 : getGyshybh().hashCode());
        result = prime * result + ((getLxr() == null) ? 0 : getLxr().hashCode());
        result = prime * result + ((getLxdh() == null) ? 0 : getLxdh().hashCode());
        result = prime * result + ((getGysjj() == null) ? 0 : getGysjj().hashCode());
        result = prime * result + ((getSsywy() == null) ? 0 : getSsywy().hashCode());
        result = prime * result + ((getTjr() == null) ? 0 : getTjr().hashCode());
        result = prime * result + ((getTjsj() == null) ? 0 : getTjsj().hashCode());
        result = prime * result + ((getZhxgr() == null) ? 0 : getZhxgr().hashCode());
        result = prime * result + ((getZhxgsj() == null) ? 0 : getZhxgsj().hashCode());
        result = prime * result + ((getBz() == null) ? 0 : getBz().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table all_gys
     *
     * @mbg.generated
     */
    public enum Column {
        gysbm("gysbm", "gysbm", "VARCHAR", false),
        ywqybm("ywqybm", "ywqybm", "INTEGER", false),
        gysmc("gysmc", "gysmc", "VARCHAR", false),
        gyshybh("gyshybh", "gyshybh", "VARCHAR", false),
        lxr("lxr", "lxr", "VARCHAR", false),
        lxdh("lxdh", "lxdh", "VARCHAR", false),
        gysjj("gysjj", "gysjj", "VARCHAR", false),
        ssywy("ssywy", "ssywy", "VARCHAR", false),
        tjr("tjr", "tjr", "VARCHAR", false),
        tjsj("tjsj", "tjsj", "TIMESTAMP", false),
        zhxgr("zhxgr", "zhxgr", "VARCHAR", false),
        zhxgsj("zhxgsj", "zhxgsj", "TIMESTAMP", false),
        bz("bz", "bz", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_gys
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}