package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AllHydjExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public AllHydjExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public AllHydjExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public AllHydjExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllHydjExample example = new AllHydjExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public AllHydjExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public AllHydjExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHydjbmIsNull() {
            addCriterion("hydjbm is null");
            return (Criteria) this;
        }

        public Criteria andHydjbmIsNotNull() {
            addCriterion("hydjbm is not null");
            return (Criteria) this;
        }

        public Criteria andHydjbmEqualTo(Integer value) {
            addCriterion("hydjbm =", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmNotEqualTo(Integer value) {
            addCriterion("hydjbm <>", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmNotEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmGreaterThan(Integer value) {
            addCriterion("hydjbm >", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmGreaterThanColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("hydjbm >=", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmGreaterThanOrEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmLessThan(Integer value) {
            addCriterion("hydjbm <", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmLessThanColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmLessThanOrEqualTo(Integer value) {
            addCriterion("hydjbm <=", value, "hydjbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjbmLessThanOrEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydjbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjbmIn(List<Integer> values) {
            addCriterion("hydjbm in", values, "hydjbm");
            return (Criteria) this;
        }

        public Criteria andHydjbmNotIn(List<Integer> values) {
            addCriterion("hydjbm not in", values, "hydjbm");
            return (Criteria) this;
        }

        public Criteria andHydjbmBetween(Integer value1, Integer value2) {
            addCriterion("hydjbm between", value1, value2, "hydjbm");
            return (Criteria) this;
        }

        public Criteria andHydjbmNotBetween(Integer value1, Integer value2) {
            addCriterion("hydjbm not between", value1, value2, "hydjbm");
            return (Criteria) this;
        }

        public Criteria andHydjIsNull() {
            addCriterion("hydj is null");
            return (Criteria) this;
        }

        public Criteria andHydjIsNotNull() {
            addCriterion("hydj is not null");
            return (Criteria) this;
        }

        public Criteria andHydjEqualTo(String value) {
            addCriterion("hydj =", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjNotEqualTo(String value) {
            addCriterion("hydj <>", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjNotEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjGreaterThan(String value) {
            addCriterion("hydj >", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjGreaterThanColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjGreaterThanOrEqualTo(String value) {
            addCriterion("hydj >=", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjGreaterThanOrEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjLessThan(String value) {
            addCriterion("hydj <", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjLessThanColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjLessThanOrEqualTo(String value) {
            addCriterion("hydj <=", value, "hydj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria andHydjLessThanOrEqualToColumn(AllHydj.Column column) {
            addCriterion(new StringBuilder("hydj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHydjLike(String value) {
            addCriterion("hydj like", value, "hydj");
            return (Criteria) this;
        }

        public Criteria andHydjNotLike(String value) {
            addCriterion("hydj not like", value, "hydj");
            return (Criteria) this;
        }

        public Criteria andHydjIn(List<String> values) {
            addCriterion("hydj in", values, "hydj");
            return (Criteria) this;
        }

        public Criteria andHydjNotIn(List<String> values) {
            addCriterion("hydj not in", values, "hydj");
            return (Criteria) this;
        }

        public Criteria andHydjBetween(String value1, String value2) {
            addCriterion("hydj between", value1, value2, "hydj");
            return (Criteria) this;
        }

        public Criteria andHydjNotBetween(String value1, String value2) {
            addCriterion("hydj not between", value1, value2, "hydj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hydj
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        private AllHydjExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        protected Criteria(AllHydjExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public AllHydjExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_hydj
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hydj
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hydj
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllHydjExample example);
    }
}