package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AllHycllxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public AllHycllxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public AllHycllxExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public AllHycllxExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllHycllxExample example = new AllHycllxExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public AllHycllxExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public AllHycllxExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHycllxbmIsNull() {
            addCriterion("hycllxbm is null");
            return (Criteria) this;
        }

        public Criteria andHycllxbmIsNotNull() {
            addCriterion("hycllxbm is not null");
            return (Criteria) this;
        }

        public Criteria andHycllxbmEqualTo(Integer value) {
            addCriterion("hycllxbm =", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmNotEqualTo(Integer value) {
            addCriterion("hycllxbm <>", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmNotEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmGreaterThan(Integer value) {
            addCriterion("hycllxbm >", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmGreaterThanColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("hycllxbm >=", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmGreaterThanOrEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmLessThan(Integer value) {
            addCriterion("hycllxbm <", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmLessThanColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmLessThanOrEqualTo(Integer value) {
            addCriterion("hycllxbm <=", value, "hycllxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxbmLessThanOrEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllxbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxbmIn(List<Integer> values) {
            addCriterion("hycllxbm in", values, "hycllxbm");
            return (Criteria) this;
        }

        public Criteria andHycllxbmNotIn(List<Integer> values) {
            addCriterion("hycllxbm not in", values, "hycllxbm");
            return (Criteria) this;
        }

        public Criteria andHycllxbmBetween(Integer value1, Integer value2) {
            addCriterion("hycllxbm between", value1, value2, "hycllxbm");
            return (Criteria) this;
        }

        public Criteria andHycllxbmNotBetween(Integer value1, Integer value2) {
            addCriterion("hycllxbm not between", value1, value2, "hycllxbm");
            return (Criteria) this;
        }

        public Criteria andHycllxIsNull() {
            addCriterion("hycllx is null");
            return (Criteria) this;
        }

        public Criteria andHycllxIsNotNull() {
            addCriterion("hycllx is not null");
            return (Criteria) this;
        }

        public Criteria andHycllxEqualTo(String value) {
            addCriterion("hycllx =", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxNotEqualTo(String value) {
            addCriterion("hycllx <>", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxNotEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxGreaterThan(String value) {
            addCriterion("hycllx >", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxGreaterThanColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxGreaterThanOrEqualTo(String value) {
            addCriterion("hycllx >=", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxGreaterThanOrEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxLessThan(String value) {
            addCriterion("hycllx <", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxLessThanColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxLessThanOrEqualTo(String value) {
            addCriterion("hycllx <=", value, "hycllx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria andHycllxLessThanOrEqualToColumn(AllHycllx.Column column) {
            addCriterion(new StringBuilder("hycllx <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHycllxLike(String value) {
            addCriterion("hycllx like", value, "hycllx");
            return (Criteria) this;
        }

        public Criteria andHycllxNotLike(String value) {
            addCriterion("hycllx not like", value, "hycllx");
            return (Criteria) this;
        }

        public Criteria andHycllxIn(List<String> values) {
            addCriterion("hycllx in", values, "hycllx");
            return (Criteria) this;
        }

        public Criteria andHycllxNotIn(List<String> values) {
            addCriterion("hycllx not in", values, "hycllx");
            return (Criteria) this;
        }

        public Criteria andHycllxBetween(String value1, String value2) {
            addCriterion("hycllx between", value1, value2, "hycllx");
            return (Criteria) this;
        }

        public Criteria andHycllxNotBetween(String value1, String value2) {
            addCriterion("hycllx not between", value1, value2, "hycllx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hycllx
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        private AllHycllxExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        protected Criteria(AllHycllxExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public AllHycllxExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_hycllx
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_hycllx
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllHycllxExample example);
    }
}