package com.yjh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class AllSpflExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public AllSpflExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public AllSpflExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public AllSpflExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllSpflExample example = new AllSpflExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public AllSpflExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public AllSpflExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpflbmIsNull() {
            addCriterion("spflbm is null");
            return (Criteria) this;
        }

        public Criteria andSpflbmIsNotNull() {
            addCriterion("spflbm is not null");
            return (Criteria) this;
        }

        public Criteria andSpflbmEqualTo(Integer value) {
            addCriterion("spflbm =", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmNotEqualTo(Integer value) {
            addCriterion("spflbm <>", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmGreaterThan(Integer value) {
            addCriterion("spflbm >", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("spflbm >=", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmLessThan(Integer value) {
            addCriterion("spflbm <", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmLessThanOrEqualTo(Integer value) {
            addCriterion("spflbm <=", value, "spflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflbmLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spflbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflbmIn(List<Integer> values) {
            addCriterion("spflbm in", values, "spflbm");
            return (Criteria) this;
        }

        public Criteria andSpflbmNotIn(List<Integer> values) {
            addCriterion("spflbm not in", values, "spflbm");
            return (Criteria) this;
        }

        public Criteria andSpflbmBetween(Integer value1, Integer value2) {
            addCriterion("spflbm between", value1, value2, "spflbm");
            return (Criteria) this;
        }

        public Criteria andSpflbmNotBetween(Integer value1, Integer value2) {
            addCriterion("spflbm not between", value1, value2, "spflbm");
            return (Criteria) this;
        }

        public Criteria andSsbkbmIsNull() {
            addCriterion("ssbkbm is null");
            return (Criteria) this;
        }

        public Criteria andSsbkbmIsNotNull() {
            addCriterion("ssbkbm is not null");
            return (Criteria) this;
        }

        public Criteria andSsbkbmEqualTo(Integer value) {
            addCriterion("ssbkbm =", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmNotEqualTo(Integer value) {
            addCriterion("ssbkbm <>", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmGreaterThan(Integer value) {
            addCriterion("ssbkbm >", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssbkbm >=", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmLessThan(Integer value) {
            addCriterion("ssbkbm <", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmLessThanOrEqualTo(Integer value) {
            addCriterion("ssbkbm <=", value, "ssbkbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSsbkbmLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("ssbkbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSsbkbmIn(List<Integer> values) {
            addCriterion("ssbkbm in", values, "ssbkbm");
            return (Criteria) this;
        }

        public Criteria andSsbkbmNotIn(List<Integer> values) {
            addCriterion("ssbkbm not in", values, "ssbkbm");
            return (Criteria) this;
        }

        public Criteria andSsbkbmBetween(Integer value1, Integer value2) {
            addCriterion("ssbkbm between", value1, value2, "ssbkbm");
            return (Criteria) this;
        }

        public Criteria andSsbkbmNotBetween(Integer value1, Integer value2) {
            addCriterion("ssbkbm not between", value1, value2, "ssbkbm");
            return (Criteria) this;
        }

        public Criteria andSpflIsNull() {
            addCriterion("spfl is null");
            return (Criteria) this;
        }

        public Criteria andSpflIsNotNull() {
            addCriterion("spfl is not null");
            return (Criteria) this;
        }

        public Criteria andSpflEqualTo(String value) {
            addCriterion("spfl =", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflNotEqualTo(String value) {
            addCriterion("spfl <>", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflGreaterThan(String value) {
            addCriterion("spfl >", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflGreaterThanOrEqualTo(String value) {
            addCriterion("spfl >=", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflLessThan(String value) {
            addCriterion("spfl <", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflLessThanOrEqualTo(String value) {
            addCriterion("spfl <=", value, "spfl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpflLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfl <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpflLike(String value) {
            addCriterion("spfl like", value, "spfl");
            return (Criteria) this;
        }

        public Criteria andSpflNotLike(String value) {
            addCriterion("spfl not like", value, "spfl");
            return (Criteria) this;
        }

        public Criteria andSpflIn(List<String> values) {
            addCriterion("spfl in", values, "spfl");
            return (Criteria) this;
        }

        public Criteria andSpflNotIn(List<String> values) {
            addCriterion("spfl not in", values, "spfl");
            return (Criteria) this;
        }

        public Criteria andSpflBetween(String value1, String value2) {
            addCriterion("spfl between", value1, value2, "spfl");
            return (Criteria) this;
        }

        public Criteria andSpflNotBetween(String value1, String value2) {
            addCriterion("spfl not between", value1, value2, "spfl");
            return (Criteria) this;
        }

        public Criteria andSjspflbmIsNull() {
            addCriterion("sjspflbm is null");
            return (Criteria) this;
        }

        public Criteria andSjspflbmIsNotNull() {
            addCriterion("sjspflbm is not null");
            return (Criteria) this;
        }

        public Criteria andSjspflbmEqualTo(Integer value) {
            addCriterion("sjspflbm =", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmNotEqualTo(Integer value) {
            addCriterion("sjspflbm <>", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmGreaterThan(Integer value) {
            addCriterion("sjspflbm >", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("sjspflbm >=", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmLessThan(Integer value) {
            addCriterion("sjspflbm <", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmLessThanOrEqualTo(Integer value) {
            addCriterion("sjspflbm <=", value, "sjspflbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSjspflbmLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sjspflbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSjspflbmIn(List<Integer> values) {
            addCriterion("sjspflbm in", values, "sjspflbm");
            return (Criteria) this;
        }

        public Criteria andSjspflbmNotIn(List<Integer> values) {
            addCriterion("sjspflbm not in", values, "sjspflbm");
            return (Criteria) this;
        }

        public Criteria andSjspflbmBetween(Integer value1, Integer value2) {
            addCriterion("sjspflbm between", value1, value2, "sjspflbm");
            return (Criteria) this;
        }

        public Criteria andSjspflbmNotBetween(Integer value1, Integer value2) {
            addCriterion("sjspflbm not between", value1, value2, "sjspflbm");
            return (Criteria) this;
        }

        public Criteria andXspxIsNull() {
            addCriterion("xspx is null");
            return (Criteria) this;
        }

        public Criteria andXspxIsNotNull() {
            addCriterion("xspx is not null");
            return (Criteria) this;
        }

        public Criteria andXspxEqualTo(Integer value) {
            addCriterion("xspx =", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxNotEqualTo(Integer value) {
            addCriterion("xspx <>", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxGreaterThan(Integer value) {
            addCriterion("xspx >", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxGreaterThanOrEqualTo(Integer value) {
            addCriterion("xspx >=", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxLessThan(Integer value) {
            addCriterion("xspx <", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxLessThanOrEqualTo(Integer value) {
            addCriterion("xspx <=", value, "xspx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andXspxLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("xspx <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andXspxIn(List<Integer> values) {
            addCriterion("xspx in", values, "xspx");
            return (Criteria) this;
        }

        public Criteria andXspxNotIn(List<Integer> values) {
            addCriterion("xspx not in", values, "xspx");
            return (Criteria) this;
        }

        public Criteria andXspxBetween(Integer value1, Integer value2) {
            addCriterion("xspx between", value1, value2, "xspx");
            return (Criteria) this;
        }

        public Criteria andXspxNotBetween(Integer value1, Integer value2) {
            addCriterion("xspx not between", value1, value2, "xspx");
            return (Criteria) this;
        }

        public Criteria andSfsxIsNull() {
            addCriterion("sfsx is null");
            return (Criteria) this;
        }

        public Criteria andSfsxIsNotNull() {
            addCriterion("sfsx is not null");
            return (Criteria) this;
        }

        public Criteria andSfsxEqualTo(Integer value) {
            addCriterion("sfsx =", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxNotEqualTo(Integer value) {
            addCriterion("sfsx <>", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxGreaterThan(Integer value) {
            addCriterion("sfsx >", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxGreaterThanOrEqualTo(Integer value) {
            addCriterion("sfsx >=", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxLessThan(Integer value) {
            addCriterion("sfsx <", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxLessThanOrEqualTo(Integer value) {
            addCriterion("sfsx <=", value, "sfsx");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSfsxLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("sfsx <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSfsxIn(List<Integer> values) {
            addCriterion("sfsx in", values, "sfsx");
            return (Criteria) this;
        }

        public Criteria andSfsxNotIn(List<Integer> values) {
            addCriterion("sfsx not in", values, "sfsx");
            return (Criteria) this;
        }

        public Criteria andSfsxBetween(Integer value1, Integer value2) {
            addCriterion("sfsx between", value1, value2, "sfsx");
            return (Criteria) this;
        }

        public Criteria andSfsxNotBetween(Integer value1, Integer value2) {
            addCriterion("sfsx not between", value1, value2, "sfsx");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjIsNull() {
            addCriterion("spfltpwj is null");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjIsNotNull() {
            addCriterion("spfltpwj is not null");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjEqualTo(String value) {
            addCriterion("spfltpwj =", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjNotEqualTo(String value) {
            addCriterion("spfltpwj <>", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjGreaterThan(String value) {
            addCriterion("spfltpwj >", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjGreaterThanOrEqualTo(String value) {
            addCriterion("spfltpwj >=", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjLessThan(String value) {
            addCriterion("spfltpwj <", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjLessThanOrEqualTo(String value) {
            addCriterion("spfltpwj <=", value, "spfltpwj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andSpfltpwjLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("spfltpwj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpfltpwjLike(String value) {
            addCriterion("spfltpwj like", value, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjNotLike(String value) {
            addCriterion("spfltpwj not like", value, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjIn(List<String> values) {
            addCriterion("spfltpwj in", values, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjNotIn(List<String> values) {
            addCriterion("spfltpwj not in", values, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjBetween(String value1, String value2) {
            addCriterion("spfltpwj between", value1, value2, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andSpfltpwjNotBetween(String value1, String value2) {
            addCriterion("spfltpwj not between", value1, value2, "spfltpwj");
            return (Criteria) this;
        }

        public Criteria andTjsjIsNull() {
            addCriterion("tjsj is null");
            return (Criteria) this;
        }

        public Criteria andTjsjIsNotNull() {
            addCriterion("tjsj is not null");
            return (Criteria) this;
        }

        public Criteria andTjsjEqualTo(LocalDateTime value) {
            addCriterion("tjsj =", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjNotEqualTo(LocalDateTime value) {
            addCriterion("tjsj <>", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjGreaterThan(LocalDateTime value) {
            addCriterion("tjsj >", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tjsj >=", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjLessThan(LocalDateTime value) {
            addCriterion("tjsj <", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tjsj <=", value, "tjsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjsjLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjsj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjsjIn(List<LocalDateTime> values) {
            addCriterion("tjsj in", values, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjNotIn(List<LocalDateTime> values) {
            addCriterion("tjsj not in", values, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tjsj between", value1, value2, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjsjNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tjsj not between", value1, value2, "tjsj");
            return (Criteria) this;
        }

        public Criteria andTjrIsNull() {
            addCriterion("tjr is null");
            return (Criteria) this;
        }

        public Criteria andTjrIsNotNull() {
            addCriterion("tjr is not null");
            return (Criteria) this;
        }

        public Criteria andTjrEqualTo(String value) {
            addCriterion("tjr =", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrNotEqualTo(String value) {
            addCriterion("tjr <>", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrGreaterThan(String value) {
            addCriterion("tjr >", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrGreaterThanOrEqualTo(String value) {
            addCriterion("tjr >=", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLessThan(String value) {
            addCriterion("tjr <", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLessThanOrEqualTo(String value) {
            addCriterion("tjr <=", value, "tjr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andTjrLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("tjr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTjrLike(String value) {
            addCriterion("tjr like", value, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotLike(String value) {
            addCriterion("tjr not like", value, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrIn(List<String> values) {
            addCriterion("tjr in", values, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotIn(List<String> values) {
            addCriterion("tjr not in", values, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrBetween(String value1, String value2) {
            addCriterion("tjr between", value1, value2, "tjr");
            return (Criteria) this;
        }

        public Criteria andTjrNotBetween(String value1, String value2) {
            addCriterion("tjr not between", value1, value2, "tjr");
            return (Criteria) this;
        }

        public Criteria andZhxgrIsNull() {
            addCriterion("zhxgr is null");
            return (Criteria) this;
        }

        public Criteria andZhxgrIsNotNull() {
            addCriterion("zhxgr is not null");
            return (Criteria) this;
        }

        public Criteria andZhxgrEqualTo(String value) {
            addCriterion("zhxgr =", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrNotEqualTo(String value) {
            addCriterion("zhxgr <>", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrGreaterThan(String value) {
            addCriterion("zhxgr >", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrGreaterThanOrEqualTo(String value) {
            addCriterion("zhxgr >=", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLessThan(String value) {
            addCriterion("zhxgr <", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLessThanOrEqualTo(String value) {
            addCriterion("zhxgr <=", value, "zhxgr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgrLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgrLike(String value) {
            addCriterion("zhxgr like", value, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotLike(String value) {
            addCriterion("zhxgr not like", value, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrIn(List<String> values) {
            addCriterion("zhxgr in", values, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotIn(List<String> values) {
            addCriterion("zhxgr not in", values, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrBetween(String value1, String value2) {
            addCriterion("zhxgr between", value1, value2, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgrNotBetween(String value1, String value2) {
            addCriterion("zhxgr not between", value1, value2, "zhxgr");
            return (Criteria) this;
        }

        public Criteria andZhxgsjIsNull() {
            addCriterion("zhxgsj is null");
            return (Criteria) this;
        }

        public Criteria andZhxgsjIsNotNull() {
            addCriterion("zhxgsj is not null");
            return (Criteria) this;
        }

        public Criteria andZhxgsjEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj =", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj <>", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjGreaterThan(LocalDateTime value) {
            addCriterion("zhxgsj >", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj >=", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjLessThan(LocalDateTime value) {
            addCriterion("zhxgsj <", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("zhxgsj <=", value, "zhxgsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andZhxgsjLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("zhxgsj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZhxgsjIn(List<LocalDateTime> values) {
            addCriterion("zhxgsj in", values, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotIn(List<LocalDateTime> values) {
            addCriterion("zhxgsj not in", values, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("zhxgsj between", value1, value2, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andZhxgsjNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("zhxgsj not between", value1, value2, "zhxgsj");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("bz <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andFldjIsNull() {
            addCriterion("fldj is null");
            return (Criteria) this;
        }

        public Criteria andFldjIsNotNull() {
            addCriterion("fldj is not null");
            return (Criteria) this;
        }

        public Criteria andFldjEqualTo(Integer value) {
            addCriterion("fldj =", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjNotEqualTo(Integer value) {
            addCriterion("fldj <>", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjNotEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjGreaterThan(Integer value) {
            addCriterion("fldj >", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjGreaterThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjGreaterThanOrEqualTo(Integer value) {
            addCriterion("fldj >=", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjGreaterThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjLessThan(Integer value) {
            addCriterion("fldj <", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjLessThanColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjLessThanOrEqualTo(Integer value) {
            addCriterion("fldj <=", value, "fldj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria andFldjLessThanOrEqualToColumn(AllSpfl.Column column) {
            addCriterion(new StringBuilder("fldj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFldjIn(List<Integer> values) {
            addCriterion("fldj in", values, "fldj");
            return (Criteria) this;
        }

        public Criteria andFldjNotIn(List<Integer> values) {
            addCriterion("fldj not in", values, "fldj");
            return (Criteria) this;
        }

        public Criteria andFldjBetween(Integer value1, Integer value2) {
            addCriterion("fldj between", value1, value2, "fldj");
            return (Criteria) this;
        }

        public Criteria andFldjNotBetween(Integer value1, Integer value2) {
            addCriterion("fldj not between", value1, value2, "fldj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spfl
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        private AllSpflExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        protected Criteria(AllSpflExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public AllSpflExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_spfl
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spfl
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spfl
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllSpflExample example);
    }
}