package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AllSpkzsxzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public AllSpkzsxzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public AllSpkzsxzExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public AllSpkzsxzExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllSpkzsxzExample example = new AllSpkzsxzExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public AllSpkzsxzExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public AllSpkzsxzExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKzsxbmIsNull() {
            addCriterion("kzsxbm is null");
            return (Criteria) this;
        }

        public Criteria andKzsxbmIsNotNull() {
            addCriterion("kzsxbm is not null");
            return (Criteria) this;
        }

        public Criteria andKzsxbmEqualTo(Integer value) {
            addCriterion("kzsxbm =", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmNotEqualTo(Integer value) {
            addCriterion("kzsxbm <>", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmNotEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmGreaterThan(Integer value) {
            addCriterion("kzsxbm >", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmGreaterThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("kzsxbm >=", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmGreaterThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmLessThan(Integer value) {
            addCriterion("kzsxbm <", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmLessThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmLessThanOrEqualTo(Integer value) {
            addCriterion("kzsxbm <=", value, "kzsxbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxbmLessThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxbmIn(List<Integer> values) {
            addCriterion("kzsxbm in", values, "kzsxbm");
            return (Criteria) this;
        }

        public Criteria andKzsxbmNotIn(List<Integer> values) {
            addCriterion("kzsxbm not in", values, "kzsxbm");
            return (Criteria) this;
        }

        public Criteria andKzsxbmBetween(Integer value1, Integer value2) {
            addCriterion("kzsxbm between", value1, value2, "kzsxbm");
            return (Criteria) this;
        }

        public Criteria andKzsxbmNotBetween(Integer value1, Integer value2) {
            addCriterion("kzsxbm not between", value1, value2, "kzsxbm");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNull() {
            addCriterion("spbm is null");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNotNull() {
            addCriterion("spbm is not null");
            return (Criteria) this;
        }

        public Criteria andSpbmEqualTo(Integer value) {
            addCriterion("spbm =", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmNotEqualTo(Integer value) {
            addCriterion("spbm <>", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmNotEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThan(Integer value) {
            addCriterion("spbm >", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmGreaterThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("spbm >=", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmGreaterThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmLessThan(Integer value) {
            addCriterion("spbm <", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmLessThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmLessThanOrEqualTo(Integer value) {
            addCriterion("spbm <=", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andSpbmLessThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("spbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmIn(List<Integer> values) {
            addCriterion("spbm in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotIn(List<Integer> values) {
            addCriterion("spbm not in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmBetween(Integer value1, Integer value2) {
            addCriterion("spbm between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotBetween(Integer value1, Integer value2) {
            addCriterion("spbm not between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andKzsxzIsNull() {
            addCriterion("kzsxz is null");
            return (Criteria) this;
        }

        public Criteria andKzsxzIsNotNull() {
            addCriterion("kzsxz is not null");
            return (Criteria) this;
        }

        public Criteria andKzsxzEqualTo(String value) {
            addCriterion("kzsxz =", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzNotEqualTo(String value) {
            addCriterion("kzsxz <>", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzNotEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzGreaterThan(String value) {
            addCriterion("kzsxz >", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzGreaterThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzGreaterThanOrEqualTo(String value) {
            addCriterion("kzsxz >=", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzGreaterThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzLessThan(String value) {
            addCriterion("kzsxz <", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzLessThanColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzLessThanOrEqualTo(String value) {
            addCriterion("kzsxz <=", value, "kzsxz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria andKzsxzLessThanOrEqualToColumn(AllSpkzsxz.Column column) {
            addCriterion(new StringBuilder("kzsxz <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andKzsxzLike(String value) {
            addCriterion("kzsxz like", value, "kzsxz");
            return (Criteria) this;
        }

        public Criteria andKzsxzNotLike(String value) {
            addCriterion("kzsxz not like", value, "kzsxz");
            return (Criteria) this;
        }

        public Criteria andKzsxzIn(List<String> values) {
            addCriterion("kzsxz in", values, "kzsxz");
            return (Criteria) this;
        }

        public Criteria andKzsxzNotIn(List<String> values) {
            addCriterion("kzsxz not in", values, "kzsxz");
            return (Criteria) this;
        }

        public Criteria andKzsxzBetween(String value1, String value2) {
            addCriterion("kzsxz between", value1, value2, "kzsxz");
            return (Criteria) this;
        }

        public Criteria andKzsxzNotBetween(String value1, String value2) {
            addCriterion("kzsxz not between", value1, value2, "kzsxz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spkzsxz
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        private AllSpkzsxzExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        protected Criteria(AllSpkzsxzExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public AllSpkzsxzExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_spkzsxz
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_spkzsxz
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllSpkzsxzExample example);
    }
}