package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class AllShdz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.dzbm
     *
     * @mbg.generated
     */
    private Integer dzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.shdr
     *
     * @mbg.generated
     */
    private String shdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.shdz
     *
     * @mbg.generated
     */
    private String shdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.sheng
     *
     * @mbg.generated
     */
    private String sheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.shi
     *
     * @mbg.generated
     */
    private String shi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.xian
     *
     * @mbg.generated
     */
    private String xian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.qybm
     *
     * @mbg.generated
     */
    private String qybm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.dhhm
     *
     * @mbg.generated
     */
    private String dhhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.sfsmrdz
     *
     * @mbg.generated
     */
    private Integer sfsmrdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_shdz.yhbm
     *
     * @mbg.generated
     */
    private Integer yhbm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.dzbm
     *
     * @return the value of all_shdz.dzbm
     *
     * @mbg.generated
     */
    public Integer getDzbm() {
        return dzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.dzbm
     *
     * @param dzbm the value for all_shdz.dzbm
     *
     * @mbg.generated
     */
    public void setDzbm(Integer dzbm) {
        this.dzbm = dzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.shdr
     *
     * @return the value of all_shdz.shdr
     *
     * @mbg.generated
     */
    public String getShdr() {
        return shdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.shdr
     *
     * @param shdr the value for all_shdz.shdr
     *
     * @mbg.generated
     */
    public void setShdr(String shdr) {
        this.shdr = shdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.shdz
     *
     * @return the value of all_shdz.shdz
     *
     * @mbg.generated
     */
    public String getShdz() {
        return shdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.shdz
     *
     * @param shdz the value for all_shdz.shdz
     *
     * @mbg.generated
     */
    public void setShdz(String shdz) {
        this.shdz = shdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.sheng
     *
     * @return the value of all_shdz.sheng
     *
     * @mbg.generated
     */
    public String getSheng() {
        return sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.sheng
     *
     * @param sheng the value for all_shdz.sheng
     *
     * @mbg.generated
     */
    public void setSheng(String sheng) {
        this.sheng = sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.shi
     *
     * @return the value of all_shdz.shi
     *
     * @mbg.generated
     */
    public String getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.shi
     *
     * @param shi the value for all_shdz.shi
     *
     * @mbg.generated
     */
    public void setShi(String shi) {
        this.shi = shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.xian
     *
     * @return the value of all_shdz.xian
     *
     * @mbg.generated
     */
    public String getXian() {
        return xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.xian
     *
     * @param xian the value for all_shdz.xian
     *
     * @mbg.generated
     */
    public void setXian(String xian) {
        this.xian = xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.qybm
     *
     * @return the value of all_shdz.qybm
     *
     * @mbg.generated
     */
    public String getQybm() {
        return qybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.qybm
     *
     * @param qybm the value for all_shdz.qybm
     *
     * @mbg.generated
     */
    public void setQybm(String qybm) {
        this.qybm = qybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.dhhm
     *
     * @return the value of all_shdz.dhhm
     *
     * @mbg.generated
     */
    public String getDhhm() {
        return dhhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.dhhm
     *
     * @param dhhm the value for all_shdz.dhhm
     *
     * @mbg.generated
     */
    public void setDhhm(String dhhm) {
        this.dhhm = dhhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.sfsmrdz
     *
     * @return the value of all_shdz.sfsmrdz
     *
     * @mbg.generated
     */
    public Integer getSfsmrdz() {
        return sfsmrdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.sfsmrdz
     *
     * @param sfsmrdz the value for all_shdz.sfsmrdz
     *
     * @mbg.generated
     */
    public void setSfsmrdz(Integer sfsmrdz) {
        this.sfsmrdz = sfsmrdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_shdz.yhbm
     *
     * @return the value of all_shdz.yhbm
     *
     * @mbg.generated
     */
    public Integer getYhbm() {
        return yhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_shdz.yhbm
     *
     * @param yhbm the value for all_shdz.yhbm
     *
     * @mbg.generated
     */
    public void setYhbm(Integer yhbm) {
        this.yhbm = yhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_shdz
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dzbm=").append(dzbm);
        sb.append(", shdr=").append(shdr);
        sb.append(", shdz=").append(shdz);
        sb.append(", sheng=").append(sheng);
        sb.append(", shi=").append(shi);
        sb.append(", xian=").append(xian);
        sb.append(", qybm=").append(qybm);
        sb.append(", dhhm=").append(dhhm);
        sb.append(", sfsmrdz=").append(sfsmrdz);
        sb.append(", yhbm=").append(yhbm);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_shdz
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AllShdz other = (AllShdz) that;
        return (this.getDzbm() == null ? other.getDzbm() == null : this.getDzbm().equals(other.getDzbm()))
            && (this.getShdr() == null ? other.getShdr() == null : this.getShdr().equals(other.getShdr()))
            && (this.getShdz() == null ? other.getShdz() == null : this.getShdz().equals(other.getShdz()))
            && (this.getSheng() == null ? other.getSheng() == null : this.getSheng().equals(other.getSheng()))
            && (this.getShi() == null ? other.getShi() == null : this.getShi().equals(other.getShi()))
            && (this.getXian() == null ? other.getXian() == null : this.getXian().equals(other.getXian()))
            && (this.getQybm() == null ? other.getQybm() == null : this.getQybm().equals(other.getQybm()))
            && (this.getDhhm() == null ? other.getDhhm() == null : this.getDhhm().equals(other.getDhhm()))
            && (this.getSfsmrdz() == null ? other.getSfsmrdz() == null : this.getSfsmrdz().equals(other.getSfsmrdz()))
            && (this.getYhbm() == null ? other.getYhbm() == null : this.getYhbm().equals(other.getYhbm()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_shdz
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDzbm() == null) ? 0 : getDzbm().hashCode());
        result = prime * result + ((getShdr() == null) ? 0 : getShdr().hashCode());
        result = prime * result + ((getShdz() == null) ? 0 : getShdz().hashCode());
        result = prime * result + ((getSheng() == null) ? 0 : getSheng().hashCode());
        result = prime * result + ((getShi() == null) ? 0 : getShi().hashCode());
        result = prime * result + ((getXian() == null) ? 0 : getXian().hashCode());
        result = prime * result + ((getQybm() == null) ? 0 : getQybm().hashCode());
        result = prime * result + ((getDhhm() == null) ? 0 : getDhhm().hashCode());
        result = prime * result + ((getSfsmrdz() == null) ? 0 : getSfsmrdz().hashCode());
        result = prime * result + ((getYhbm() == null) ? 0 : getYhbm().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table all_shdz
     *
     * @mbg.generated
     */
    public enum Column {
        dzbm("dzbm", "dzbm", "INTEGER", false),
        shdr("shdr", "shdr", "VARCHAR", false),
        shdz("shdz", "shdz", "VARCHAR", false),
        sheng("sheng", "sheng", "VARCHAR", false),
        shi("shi", "shi", "VARCHAR", false),
        xian("xian", "xian", "VARCHAR", false),
        qybm("qybm", "qybm", "VARCHAR", false),
        dhhm("dhhm", "dhhm", "VARCHAR", false),
        sfsmrdz("sfsmrdz", "sfsmrdz", "INTEGER", false),
        yhbm("yhbm", "yhbm", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_shdz
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}