package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AllZffsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public AllZffsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public AllZffsExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public AllZffsExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllZffsExample example = new AllZffsExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public AllZffsExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public AllZffsExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZffsbmIsNull() {
            addCriterion("zffsbm is null");
            return (Criteria) this;
        }

        public Criteria andZffsbmIsNotNull() {
            addCriterion("zffsbm is not null");
            return (Criteria) this;
        }

        public Criteria andZffsbmEqualTo(Integer value) {
            addCriterion("zffsbm =", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmNotEqualTo(Integer value) {
            addCriterion("zffsbm <>", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmNotEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmGreaterThan(Integer value) {
            addCriterion("zffsbm >", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmGreaterThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("zffsbm >=", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmGreaterThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmLessThan(Integer value) {
            addCriterion("zffsbm <", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmLessThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmLessThanOrEqualTo(Integer value) {
            addCriterion("zffsbm <=", value, "zffsbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsbmLessThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffsbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsbmIn(List<Integer> values) {
            addCriterion("zffsbm in", values, "zffsbm");
            return (Criteria) this;
        }

        public Criteria andZffsbmNotIn(List<Integer> values) {
            addCriterion("zffsbm not in", values, "zffsbm");
            return (Criteria) this;
        }

        public Criteria andZffsbmBetween(Integer value1, Integer value2) {
            addCriterion("zffsbm between", value1, value2, "zffsbm");
            return (Criteria) this;
        }

        public Criteria andZffsbmNotBetween(Integer value1, Integer value2) {
            addCriterion("zffsbm not between", value1, value2, "zffsbm");
            return (Criteria) this;
        }

        public Criteria andZffsIsNull() {
            addCriterion("zffs is null");
            return (Criteria) this;
        }

        public Criteria andZffsIsNotNull() {
            addCriterion("zffs is not null");
            return (Criteria) this;
        }

        public Criteria andZffsEqualTo(String value) {
            addCriterion("zffs =", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsNotEqualTo(String value) {
            addCriterion("zffs <>", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsNotEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsGreaterThan(String value) {
            addCriterion("zffs >", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsGreaterThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsGreaterThanOrEqualTo(String value) {
            addCriterion("zffs >=", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsGreaterThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsLessThan(String value) {
            addCriterion("zffs <", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsLessThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsLessThanOrEqualTo(String value) {
            addCriterion("zffs <=", value, "zffs");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andZffsLessThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("zffs <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZffsLike(String value) {
            addCriterion("zffs like", value, "zffs");
            return (Criteria) this;
        }

        public Criteria andZffsNotLike(String value) {
            addCriterion("zffs not like", value, "zffs");
            return (Criteria) this;
        }

        public Criteria andZffsIn(List<String> values) {
            addCriterion("zffs in", values, "zffs");
            return (Criteria) this;
        }

        public Criteria andZffsNotIn(List<String> values) {
            addCriterion("zffs not in", values, "zffs");
            return (Criteria) this;
        }

        public Criteria andZffsBetween(String value1, String value2) {
            addCriterion("zffs between", value1, value2, "zffs");
            return (Criteria) this;
        }

        public Criteria andZffsNotBetween(String value1, String value2) {
            addCriterion("zffs not between", value1, value2, "zffs");
            return (Criteria) this;
        }

        public Criteria andSmIsNull() {
            addCriterion("sm is null");
            return (Criteria) this;
        }

        public Criteria andSmIsNotNull() {
            addCriterion("sm is not null");
            return (Criteria) this;
        }

        public Criteria andSmEqualTo(String value) {
            addCriterion("sm =", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmNotEqualTo(String value) {
            addCriterion("sm <>", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmNotEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmGreaterThan(String value) {
            addCriterion("sm >", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmGreaterThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmGreaterThanOrEqualTo(String value) {
            addCriterion("sm >=", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmGreaterThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmLessThan(String value) {
            addCriterion("sm <", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmLessThanColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmLessThanOrEqualTo(String value) {
            addCriterion("sm <=", value, "sm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria andSmLessThanOrEqualToColumn(AllZffs.Column column) {
            addCriterion(new StringBuilder("sm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSmLike(String value) {
            addCriterion("sm like", value, "sm");
            return (Criteria) this;
        }

        public Criteria andSmNotLike(String value) {
            addCriterion("sm not like", value, "sm");
            return (Criteria) this;
        }

        public Criteria andSmIn(List<String> values) {
            addCriterion("sm in", values, "sm");
            return (Criteria) this;
        }

        public Criteria andSmNotIn(List<String> values) {
            addCriterion("sm not in", values, "sm");
            return (Criteria) this;
        }

        public Criteria andSmBetween(String value1, String value2) {
            addCriterion("sm between", value1, value2, "sm");
            return (Criteria) this;
        }

        public Criteria andSmNotBetween(String value1, String value2) {
            addCriterion("sm not between", value1, value2, "sm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_zffs
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        private AllZffsExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        protected Criteria(AllZffsExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public AllZffsExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_zffs
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_zffs
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_zffs
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.AllZffsExample example);
    }
}