package com.yjh.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class HyHyzt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy_hyzt.hyztbm
     *
     * @mbg.generated
     */
    private Integer hyztbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy_hyzt.hyzt
     *
     * @mbg.generated
     */
    private String hyzt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy_hyzt.hyztbm
     *
     * @return the value of hy_hyzt.hyztbm
     *
     * @mbg.generated
     */
    public Integer getHyztbm() {
        return hyztbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy_hyzt.hyztbm
     *
     * @param hyztbm the value for hy_hyzt.hyztbm
     *
     * @mbg.generated
     */
    public void setHyztbm(Integer hyztbm) {
        this.hyztbm = hyztbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy_hyzt.hyzt
     *
     * @return the value of hy_hyzt.hyzt
     *
     * @mbg.generated
     */
    public String getHyzt() {
        return hyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy_hyzt.hyzt
     *
     * @param hyzt the value for hy_hyzt.hyzt
     *
     * @mbg.generated
     */
    public void setHyzt(String hyzt) {
        this.hyzt = hyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_hyzt
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hyztbm=").append(hyztbm);
        sb.append(", hyzt=").append(hyzt);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_hyzt
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HyHyzt other = (HyHyzt) that;
        return (this.getHyztbm() == null ? other.getHyztbm() == null : this.getHyztbm().equals(other.getHyztbm()))
            && (this.getHyzt() == null ? other.getHyzt() == null : this.getHyzt().equals(other.getHyzt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_hyzt
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHyztbm() == null) ? 0 : getHyztbm().hashCode());
        result = prime * result + ((getHyzt() == null) ? 0 : getHyzt().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hy_hyzt
     *
     * @mbg.generated
     */
    public enum Column {
        hyztbm("hyztbm", "hyztbm", "INTEGER", false),
        hyzt("hyzt", "hyzt", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_hyzt
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}