package com.yjh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class HyShjlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public HyShjlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public HyShjlExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public HyShjlExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        HyShjlExample example = new HyShjlExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public HyShjlExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public HyShjlExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHyshjlbmIsNull() {
            addCriterion("hyshjlbm is null");
            return (Criteria) this;
        }

        public Criteria andHyshjlbmIsNotNull() {
            addCriterion("hyshjlbm is not null");
            return (Criteria) this;
        }

        public Criteria andHyshjlbmEqualTo(Long value) {
            addCriterion("hyshjlbm =", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmNotEqualTo(Long value) {
            addCriterion("hyshjlbm <>", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmGreaterThan(Long value) {
            addCriterion("hyshjlbm >", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmGreaterThanOrEqualTo(Long value) {
            addCriterion("hyshjlbm >=", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmLessThan(Long value) {
            addCriterion("hyshjlbm <", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmLessThanOrEqualTo(Long value) {
            addCriterion("hyshjlbm <=", value, "hyshjlbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHyshjlbmLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hyshjlbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHyshjlbmIn(List<Long> values) {
            addCriterion("hyshjlbm in", values, "hyshjlbm");
            return (Criteria) this;
        }

        public Criteria andHyshjlbmNotIn(List<Long> values) {
            addCriterion("hyshjlbm not in", values, "hyshjlbm");
            return (Criteria) this;
        }

        public Criteria andHyshjlbmBetween(Long value1, Long value2) {
            addCriterion("hyshjlbm between", value1, value2, "hyshjlbm");
            return (Criteria) this;
        }

        public Criteria andHyshjlbmNotBetween(Long value1, Long value2) {
            addCriterion("hyshjlbm not between", value1, value2, "hyshjlbm");
            return (Criteria) this;
        }

        public Criteria andShztbmIsNull() {
            addCriterion("shztbm is null");
            return (Criteria) this;
        }

        public Criteria andShztbmIsNotNull() {
            addCriterion("shztbm is not null");
            return (Criteria) this;
        }

        public Criteria andShztbmEqualTo(Integer value) {
            addCriterion("shztbm =", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmNotEqualTo(Integer value) {
            addCriterion("shztbm <>", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmGreaterThan(Integer value) {
            addCriterion("shztbm >", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("shztbm >=", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmLessThan(Integer value) {
            addCriterion("shztbm <", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmLessThanOrEqualTo(Integer value) {
            addCriterion("shztbm <=", value, "shztbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShztbmLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shztbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShztbmIn(List<Integer> values) {
            addCriterion("shztbm in", values, "shztbm");
            return (Criteria) this;
        }

        public Criteria andShztbmNotIn(List<Integer> values) {
            addCriterion("shztbm not in", values, "shztbm");
            return (Criteria) this;
        }

        public Criteria andShztbmBetween(Integer value1, Integer value2) {
            addCriterion("shztbm between", value1, value2, "shztbm");
            return (Criteria) this;
        }

        public Criteria andShztbmNotBetween(Integer value1, Integer value2) {
            addCriterion("shztbm not between", value1, value2, "shztbm");
            return (Criteria) this;
        }

        public Criteria andHybhIsNull() {
            addCriterion("hybh is null");
            return (Criteria) this;
        }

        public Criteria andHybhIsNotNull() {
            addCriterion("hybh is not null");
            return (Criteria) this;
        }

        public Criteria andHybhEqualTo(String value) {
            addCriterion("hybh =", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhNotEqualTo(String value) {
            addCriterion("hybh <>", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhGreaterThan(String value) {
            addCriterion("hybh >", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhGreaterThanOrEqualTo(String value) {
            addCriterion("hybh >=", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhLessThan(String value) {
            addCriterion("hybh <", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhLessThanOrEqualTo(String value) {
            addCriterion("hybh <=", value, "hybh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andHybhLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("hybh <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andHybhLike(String value) {
            addCriterion("hybh like", value, "hybh");
            return (Criteria) this;
        }

        public Criteria andHybhNotLike(String value) {
            addCriterion("hybh not like", value, "hybh");
            return (Criteria) this;
        }

        public Criteria andHybhIn(List<String> values) {
            addCriterion("hybh in", values, "hybh");
            return (Criteria) this;
        }

        public Criteria andHybhNotIn(List<String> values) {
            addCriterion("hybh not in", values, "hybh");
            return (Criteria) this;
        }

        public Criteria andHybhBetween(String value1, String value2) {
            addCriterion("hybh between", value1, value2, "hybh");
            return (Criteria) this;
        }

        public Criteria andHybhNotBetween(String value1, String value2) {
            addCriterion("hybh not between", value1, value2, "hybh");
            return (Criteria) this;
        }

        public Criteria andShrIsNull() {
            addCriterion("shr is null");
            return (Criteria) this;
        }

        public Criteria andShrIsNotNull() {
            addCriterion("shr is not null");
            return (Criteria) this;
        }

        public Criteria andShrEqualTo(String value) {
            addCriterion("shr =", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrNotEqualTo(String value) {
            addCriterion("shr <>", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrGreaterThan(String value) {
            addCriterion("shr >", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrGreaterThanOrEqualTo(String value) {
            addCriterion("shr >=", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrLessThan(String value) {
            addCriterion("shr <", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrLessThanOrEqualTo(String value) {
            addCriterion("shr <=", value, "shr");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShrLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shr <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShrLike(String value) {
            addCriterion("shr like", value, "shr");
            return (Criteria) this;
        }

        public Criteria andShrNotLike(String value) {
            addCriterion("shr not like", value, "shr");
            return (Criteria) this;
        }

        public Criteria andShrIn(List<String> values) {
            addCriterion("shr in", values, "shr");
            return (Criteria) this;
        }

        public Criteria andShrNotIn(List<String> values) {
            addCriterion("shr not in", values, "shr");
            return (Criteria) this;
        }

        public Criteria andShrBetween(String value1, String value2) {
            addCriterion("shr between", value1, value2, "shr");
            return (Criteria) this;
        }

        public Criteria andShrNotBetween(String value1, String value2) {
            addCriterion("shr not between", value1, value2, "shr");
            return (Criteria) this;
        }

        public Criteria andShsjIsNull() {
            addCriterion("shsj is null");
            return (Criteria) this;
        }

        public Criteria andShsjIsNotNull() {
            addCriterion("shsj is not null");
            return (Criteria) this;
        }

        public Criteria andShsjEqualTo(LocalDateTime value) {
            addCriterion("shsj =", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjNotEqualTo(LocalDateTime value) {
            addCriterion("shsj <>", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjGreaterThan(LocalDateTime value) {
            addCriterion("shsj >", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("shsj >=", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjLessThan(LocalDateTime value) {
            addCriterion("shsj <", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("shsj <=", value, "shsj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andShsjLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("shsj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShsjIn(List<LocalDateTime> values) {
            addCriterion("shsj in", values, "shsj");
            return (Criteria) this;
        }

        public Criteria andShsjNotIn(List<LocalDateTime> values) {
            addCriterion("shsj not in", values, "shsj");
            return (Criteria) this;
        }

        public Criteria andShsjBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("shsj between", value1, value2, "shsj");
            return (Criteria) this;
        }

        public Criteria andShsjNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("shsj not between", value1, value2, "shsj");
            return (Criteria) this;
        }

        public Criteria andYysmIsNull() {
            addCriterion("yysm is null");
            return (Criteria) this;
        }

        public Criteria andYysmIsNotNull() {
            addCriterion("yysm is not null");
            return (Criteria) this;
        }

        public Criteria andYysmEqualTo(String value) {
            addCriterion("yysm =", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmNotEqualTo(String value) {
            addCriterion("yysm <>", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmNotEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmGreaterThan(String value) {
            addCriterion("yysm >", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmGreaterThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmGreaterThanOrEqualTo(String value) {
            addCriterion("yysm >=", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmGreaterThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmLessThan(String value) {
            addCriterion("yysm <", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmLessThanColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmLessThanOrEqualTo(String value) {
            addCriterion("yysm <=", value, "yysm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria andYysmLessThanOrEqualToColumn(HyShjl.Column column) {
            addCriterion(new StringBuilder("yysm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andYysmLike(String value) {
            addCriterion("yysm like", value, "yysm");
            return (Criteria) this;
        }

        public Criteria andYysmNotLike(String value) {
            addCriterion("yysm not like", value, "yysm");
            return (Criteria) this;
        }

        public Criteria andYysmIn(List<String> values) {
            addCriterion("yysm in", values, "yysm");
            return (Criteria) this;
        }

        public Criteria andYysmNotIn(List<String> values) {
            addCriterion("yysm not in", values, "yysm");
            return (Criteria) this;
        }

        public Criteria andYysmBetween(String value1, String value2) {
            addCriterion("yysm between", value1, value2, "yysm");
            return (Criteria) this;
        }

        public Criteria andYysmNotBetween(String value1, String value2) {
            addCriterion("yysm not between", value1, value2, "yysm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hy_shjl
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        private HyShjlExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        protected Criteria(HyShjlExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public HyShjlExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table hy_shjl
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hy_shjl
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hy_shjl
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.HyShjlExample example);
    }
}