package com.yjh.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class XsDd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.ddbm
     *
     * @mbg.generated
     */
    private Long ddbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.zffsbm
     *
     * @mbg.generated
     */
    private Integer zffsbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.ddlxbm
     *
     * @mbg.generated
     */
    private Integer ddlxbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.ddztbm
     *
     * @mbg.generated
     */
    private Integer ddztbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.ddh
     *
     * @mbg.generated
     */
    private String ddh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.xdsj
     *
     * @mbg.generated
     */
    private LocalDateTime xdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.ddze
     *
     * @mbg.generated
     */
    private BigDecimal ddze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.mjhyh
     *
     * @mbg.generated
     */
    private String mjhyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.shr
     *
     * @mbg.generated
     */
    private String shr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.lxdh
     *
     * @mbg.generated
     */
    private String lxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.zfsj
     *
     * @mbg.generated
     */
    private LocalDateTime zfsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xs_dd.wcsj
     *
     * @mbg.generated
     */
    private LocalDateTime wcsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.ddbm
     *
     * @return the value of xs_dd.ddbm
     *
     * @mbg.generated
     */
    public Long getDdbm() {
        return ddbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.ddbm
     *
     * @param ddbm the value for xs_dd.ddbm
     *
     * @mbg.generated
     */
    public void setDdbm(Long ddbm) {
        this.ddbm = ddbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.zffsbm
     *
     * @return the value of xs_dd.zffsbm
     *
     * @mbg.generated
     */
    public Integer getZffsbm() {
        return zffsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.zffsbm
     *
     * @param zffsbm the value for xs_dd.zffsbm
     *
     * @mbg.generated
     */
    public void setZffsbm(Integer zffsbm) {
        this.zffsbm = zffsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.ddlxbm
     *
     * @return the value of xs_dd.ddlxbm
     *
     * @mbg.generated
     */
    public Integer getDdlxbm() {
        return ddlxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.ddlxbm
     *
     * @param ddlxbm the value for xs_dd.ddlxbm
     *
     * @mbg.generated
     */
    public void setDdlxbm(Integer ddlxbm) {
        this.ddlxbm = ddlxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.ddztbm
     *
     * @return the value of xs_dd.ddztbm
     *
     * @mbg.generated
     */
    public Integer getDdztbm() {
        return ddztbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.ddztbm
     *
     * @param ddztbm the value for xs_dd.ddztbm
     *
     * @mbg.generated
     */
    public void setDdztbm(Integer ddztbm) {
        this.ddztbm = ddztbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.ddh
     *
     * @return the value of xs_dd.ddh
     *
     * @mbg.generated
     */
    public String getDdh() {
        return ddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.ddh
     *
     * @param ddh the value for xs_dd.ddh
     *
     * @mbg.generated
     */
    public void setDdh(String ddh) {
        this.ddh = ddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.xdsj
     *
     * @return the value of xs_dd.xdsj
     *
     * @mbg.generated
     */
    public LocalDateTime getXdsj() {
        return xdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.xdsj
     *
     * @param xdsj the value for xs_dd.xdsj
     *
     * @mbg.generated
     */
    public void setXdsj(LocalDateTime xdsj) {
        this.xdsj = xdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.ddze
     *
     * @return the value of xs_dd.ddze
     *
     * @mbg.generated
     */
    public BigDecimal getDdze() {
        return ddze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.ddze
     *
     * @param ddze the value for xs_dd.ddze
     *
     * @mbg.generated
     */
    public void setDdze(BigDecimal ddze) {
        this.ddze = ddze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.mjhyh
     *
     * @return the value of xs_dd.mjhyh
     *
     * @mbg.generated
     */
    public String getMjhyh() {
        return mjhyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.mjhyh
     *
     * @param mjhyh the value for xs_dd.mjhyh
     *
     * @mbg.generated
     */
    public void setMjhyh(String mjhyh) {
        this.mjhyh = mjhyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.shr
     *
     * @return the value of xs_dd.shr
     *
     * @mbg.generated
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.shr
     *
     * @param shr the value for xs_dd.shr
     *
     * @mbg.generated
     */
    public void setShr(String shr) {
        this.shr = shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.lxdh
     *
     * @return the value of xs_dd.lxdh
     *
     * @mbg.generated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.lxdh
     *
     * @param lxdh the value for xs_dd.lxdh
     *
     * @mbg.generated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.zfsj
     *
     * @return the value of xs_dd.zfsj
     *
     * @mbg.generated
     */
    public LocalDateTime getZfsj() {
        return zfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.zfsj
     *
     * @param zfsj the value for xs_dd.zfsj
     *
     * @mbg.generated
     */
    public void setZfsj(LocalDateTime zfsj) {
        this.zfsj = zfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xs_dd.wcsj
     *
     * @return the value of xs_dd.wcsj
     *
     * @mbg.generated
     */
    public LocalDateTime getWcsj() {
        return wcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xs_dd.wcsj
     *
     * @param wcsj the value for xs_dd.wcsj
     *
     * @mbg.generated
     */
    public void setWcsj(LocalDateTime wcsj) {
        this.wcsj = wcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_dd
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ddbm=").append(ddbm);
        sb.append(", zffsbm=").append(zffsbm);
        sb.append(", ddlxbm=").append(ddlxbm);
        sb.append(", ddztbm=").append(ddztbm);
        sb.append(", ddh=").append(ddh);
        sb.append(", xdsj=").append(xdsj);
        sb.append(", ddze=").append(ddze);
        sb.append(", mjhyh=").append(mjhyh);
        sb.append(", shr=").append(shr);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", zfsj=").append(zfsj);
        sb.append(", wcsj=").append(wcsj);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_dd
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XsDd other = (XsDd) that;
        return (this.getDdbm() == null ? other.getDdbm() == null : this.getDdbm().equals(other.getDdbm()))
            && (this.getZffsbm() == null ? other.getZffsbm() == null : this.getZffsbm().equals(other.getZffsbm()))
            && (this.getDdlxbm() == null ? other.getDdlxbm() == null : this.getDdlxbm().equals(other.getDdlxbm()))
            && (this.getDdztbm() == null ? other.getDdztbm() == null : this.getDdztbm().equals(other.getDdztbm()))
            && (this.getDdh() == null ? other.getDdh() == null : this.getDdh().equals(other.getDdh()))
            && (this.getXdsj() == null ? other.getXdsj() == null : this.getXdsj().equals(other.getXdsj()))
            && (this.getDdze() == null ? other.getDdze() == null : this.getDdze().equals(other.getDdze()))
            && (this.getMjhyh() == null ? other.getMjhyh() == null : this.getMjhyh().equals(other.getMjhyh()))
            && (this.getShr() == null ? other.getShr() == null : this.getShr().equals(other.getShr()))
            && (this.getLxdh() == null ? other.getLxdh() == null : this.getLxdh().equals(other.getLxdh()))
            && (this.getZfsj() == null ? other.getZfsj() == null : this.getZfsj().equals(other.getZfsj()))
            && (this.getWcsj() == null ? other.getWcsj() == null : this.getWcsj().equals(other.getWcsj()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_dd
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDdbm() == null) ? 0 : getDdbm().hashCode());
        result = prime * result + ((getZffsbm() == null) ? 0 : getZffsbm().hashCode());
        result = prime * result + ((getDdlxbm() == null) ? 0 : getDdlxbm().hashCode());
        result = prime * result + ((getDdztbm() == null) ? 0 : getDdztbm().hashCode());
        result = prime * result + ((getDdh() == null) ? 0 : getDdh().hashCode());
        result = prime * result + ((getXdsj() == null) ? 0 : getXdsj().hashCode());
        result = prime * result + ((getDdze() == null) ? 0 : getDdze().hashCode());
        result = prime * result + ((getMjhyh() == null) ? 0 : getMjhyh().hashCode());
        result = prime * result + ((getShr() == null) ? 0 : getShr().hashCode());
        result = prime * result + ((getLxdh() == null) ? 0 : getLxdh().hashCode());
        result = prime * result + ((getZfsj() == null) ? 0 : getZfsj().hashCode());
        result = prime * result + ((getWcsj() == null) ? 0 : getWcsj().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table xs_dd
     *
     * @mbg.generated
     */
    public enum Column {
        ddbm("ddbm", "ddbm", "BIGINT", false),
        zffsbm("zffsbm", "zffsbm", "INTEGER", false),
        ddlxbm("ddlxbm", "ddlxbm", "INTEGER", false),
        ddztbm("ddztbm", "ddztbm", "INTEGER", false),
        ddh("ddh", "ddh", "VARCHAR", false),
        xdsj("xdsj", "xdsj", "TIMESTAMP", false),
        ddze("ddze", "ddze", "NUMERIC", false),
        mjhyh("mjhyh", "mjhyh", "VARCHAR", false),
        shr("shr", "shr", "VARCHAR", false),
        lxdh("lxdh", "lxdh", "VARCHAR", false),
        zfsj("zfsj", "zfsj", "TIMESTAMP", false),
        wcsj("wcsj", "wcsj", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_dd
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}