package com.yjh.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class XsDdmxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public XsDdmxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public XsDdmxExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public XsDdmxExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        XsDdmxExample example = new XsDdmxExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public XsDdmxExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public XsDdmxExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDdmxhIsNull() {
            addCriterion("ddmxh is null");
            return (Criteria) this;
        }

        public Criteria andDdmxhIsNotNull() {
            addCriterion("ddmxh is not null");
            return (Criteria) this;
        }

        public Criteria andDdmxhEqualTo(Long value) {
            addCriterion("ddmxh =", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhNotEqualTo(Long value) {
            addCriterion("ddmxh <>", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhGreaterThan(Long value) {
            addCriterion("ddmxh >", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhGreaterThanOrEqualTo(Long value) {
            addCriterion("ddmxh >=", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhLessThan(Long value) {
            addCriterion("ddmxh <", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhLessThanOrEqualTo(Long value) {
            addCriterion("ddmxh <=", value, "ddmxh");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdmxhLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddmxh <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdmxhIn(List<Long> values) {
            addCriterion("ddmxh in", values, "ddmxh");
            return (Criteria) this;
        }

        public Criteria andDdmxhNotIn(List<Long> values) {
            addCriterion("ddmxh not in", values, "ddmxh");
            return (Criteria) this;
        }

        public Criteria andDdmxhBetween(Long value1, Long value2) {
            addCriterion("ddmxh between", value1, value2, "ddmxh");
            return (Criteria) this;
        }

        public Criteria andDdmxhNotBetween(Long value1, Long value2) {
            addCriterion("ddmxh not between", value1, value2, "ddmxh");
            return (Criteria) this;
        }

        public Criteria andDdbmIsNull() {
            addCriterion("ddbm is null");
            return (Criteria) this;
        }

        public Criteria andDdbmIsNotNull() {
            addCriterion("ddbm is not null");
            return (Criteria) this;
        }

        public Criteria andDdbmEqualTo(Long value) {
            addCriterion("ddbm =", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmNotEqualTo(Long value) {
            addCriterion("ddbm <>", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmGreaterThan(Long value) {
            addCriterion("ddbm >", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmGreaterThanOrEqualTo(Long value) {
            addCriterion("ddbm >=", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmLessThan(Long value) {
            addCriterion("ddbm <", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmLessThanOrEqualTo(Long value) {
            addCriterion("ddbm <=", value, "ddbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andDdbmLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("ddbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDdbmIn(List<Long> values) {
            addCriterion("ddbm in", values, "ddbm");
            return (Criteria) this;
        }

        public Criteria andDdbmNotIn(List<Long> values) {
            addCriterion("ddbm not in", values, "ddbm");
            return (Criteria) this;
        }

        public Criteria andDdbmBetween(Long value1, Long value2) {
            addCriterion("ddbm between", value1, value2, "ddbm");
            return (Criteria) this;
        }

        public Criteria andDdbmNotBetween(Long value1, Long value2) {
            addCriterion("ddbm not between", value1, value2, "ddbm");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNull() {
            addCriterion("spbm is null");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNotNull() {
            addCriterion("spbm is not null");
            return (Criteria) this;
        }

        public Criteria andSpbmEqualTo(Integer value) {
            addCriterion("spbm =", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmNotEqualTo(Integer value) {
            addCriterion("spbm <>", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThan(Integer value) {
            addCriterion("spbm >", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("spbm >=", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmLessThan(Integer value) {
            addCriterion("spbm <", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmLessThanOrEqualTo(Integer value) {
            addCriterion("spbm <=", value, "spbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpbmLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpbmIn(List<Integer> values) {
            addCriterion("spbm in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotIn(List<Integer> values) {
            addCriterion("spbm not in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmBetween(Integer value1, Integer value2) {
            addCriterion("spbm between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotBetween(Integer value1, Integer value2) {
            addCriterion("spbm not between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmIsNull() {
            addCriterion("spggsxzbm is null");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmIsNotNull() {
            addCriterion("spggsxzbm is not null");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmEqualTo(Integer value) {
            addCriterion("spggsxzbm =", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmNotEqualTo(Integer value) {
            addCriterion("spggsxzbm <>", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmGreaterThan(Integer value) {
            addCriterion("spggsxzbm >", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("spggsxzbm >=", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmLessThan(Integer value) {
            addCriterion("spggsxzbm <", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmLessThanOrEqualTo(Integer value) {
            addCriterion("spggsxzbm <=", value, "spggsxzbm");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpggsxzbmLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spggsxzbm <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmIn(List<Integer> values) {
            addCriterion("spggsxzbm in", values, "spggsxzbm");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmNotIn(List<Integer> values) {
            addCriterion("spggsxzbm not in", values, "spggsxzbm");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmBetween(Integer value1, Integer value2) {
            addCriterion("spggsxzbm between", value1, value2, "spggsxzbm");
            return (Criteria) this;
        }

        public Criteria andSpggsxzbmNotBetween(Integer value1, Integer value2) {
            addCriterion("spggsxzbm not between", value1, value2, "spggsxzbm");
            return (Criteria) this;
        }

        public Criteria andSpdjIsNull() {
            addCriterion("spdj is null");
            return (Criteria) this;
        }

        public Criteria andSpdjIsNotNull() {
            addCriterion("spdj is not null");
            return (Criteria) this;
        }

        public Criteria andSpdjEqualTo(BigDecimal value) {
            addCriterion("spdj =", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjNotEqualTo(BigDecimal value) {
            addCriterion("spdj <>", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjGreaterThan(BigDecimal value) {
            addCriterion("spdj >", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("spdj >=", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjLessThan(BigDecimal value) {
            addCriterion("spdj <", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjLessThanOrEqualTo(BigDecimal value) {
            addCriterion("spdj <=", value, "spdj");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpdjLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spdj <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpdjIn(List<BigDecimal> values) {
            addCriterion("spdj in", values, "spdj");
            return (Criteria) this;
        }

        public Criteria andSpdjNotIn(List<BigDecimal> values) {
            addCriterion("spdj not in", values, "spdj");
            return (Criteria) this;
        }

        public Criteria andSpdjBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spdj between", value1, value2, "spdj");
            return (Criteria) this;
        }

        public Criteria andSpdjNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spdj not between", value1, value2, "spdj");
            return (Criteria) this;
        }

        public Criteria andSpslIsNull() {
            addCriterion("spsl is null");
            return (Criteria) this;
        }

        public Criteria andSpslIsNotNull() {
            addCriterion("spsl is not null");
            return (Criteria) this;
        }

        public Criteria andSpslEqualTo(BigDecimal value) {
            addCriterion("spsl =", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslNotEqualTo(BigDecimal value) {
            addCriterion("spsl <>", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslGreaterThan(BigDecimal value) {
            addCriterion("spsl >", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("spsl >=", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslLessThan(BigDecimal value) {
            addCriterion("spsl <", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslLessThanOrEqualTo(BigDecimal value) {
            addCriterion("spsl <=", value, "spsl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andSpslLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("spsl <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSpslIn(List<BigDecimal> values) {
            addCriterion("spsl in", values, "spsl");
            return (Criteria) this;
        }

        public Criteria andSpslNotIn(List<BigDecimal> values) {
            addCriterion("spsl not in", values, "spsl");
            return (Criteria) this;
        }

        public Criteria andSpslBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spsl between", value1, value2, "spsl");
            return (Criteria) this;
        }

        public Criteria andSpslNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spsl not between", value1, value2, "spsl");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("je is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("je is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("je =", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("je <>", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("je >", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("je >=", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("je <", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("je <=", value, "je");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andJeLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("je <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("je in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("je not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("je between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("je not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzNotEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzGreaterThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria andBzLessThanOrEqualToColumn(XsDdmx.Column column) {
            addCriterion(new StringBuilder("bz <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xs_ddmx
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        private XsDdmxExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        protected Criteria(XsDdmxExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public XsDdmxExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table xs_ddmx
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xs_ddmx
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table xs_ddmx
         *
         * @mbg.generated
         */
        void example(com.yjh.db.domain.XsDdmxExample example);
    }
}