USE [master]
GO

/****** Object:  Database [yjh]    Script Date: 2019/8/10 13:43:13 ******/
DROP DATABASE [yjh]
GO

/****** Object:  Database [yjh]    Script Date: 2019/8/10 13:43:13 ******/
CREATE DATABASE [yjh]
CONTAINMENT = NONE
ON  PRIMARY
  ( NAME = N'yjh', FILENAME = N'D:\sqlserver\MSSQL14.MSSQLSERVER\MSSQL\DATA\yjh.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
LOG ON
  ( NAME = N'yjh_log', FILENAME = N'D:\sqlserver\MSSQL14.MSSQLSERVER\MSSQL\DATA\yjh_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
  begin
    EXEC [yjh].[dbo].[sp_fulltext_database] @action = 'enable'
  end
GO

ALTER DATABASE [yjh] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [yjh] SET ANSI_NULLS OFF
GO

ALTER DATABASE [yjh] SET ANSI_PADDING OFF
GO

ALTER DATABASE [yjh] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [yjh] SET ARITHABORT OFF
GO

ALTER DATABASE [yjh] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [yjh] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [yjh] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [yjh] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [yjh] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [yjh] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [yjh] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [yjh] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [yjh] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [yjh] SET  DISABLE_BROKER
GO

ALTER DATABASE [yjh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [yjh] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [yjh] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [yjh] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [yjh] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [yjh] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [yjh] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [yjh] SET RECOVERY FULL
GO

ALTER DATABASE [yjh] SET  MULTI_USER
GO

ALTER DATABASE [yjh] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [yjh] SET DB_CHAINING OFF
GO

ALTER DATABASE [yjh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [yjh] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [yjh] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [yjh] SET QUERY_STORE = OFF
GO

ALTER DATABASE [yjh] SET  READ_WRITE
GO


