package com.yjh.db.dao;

import com.yjh.db.domain.AllHycllx;
import com.yjh.db.domain.AllHycllxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllHycllxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    long countByExample(AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int deleteByExample(AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hycllxbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int insert(AllHycllx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int insertSelective(AllHycllx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    AllHycllx selectOneByExample(AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    AllHycllx selectOneByExampleSelective(@Param("example") AllHycllxExample example, @Param("selective") AllHycllx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    List<AllHycllx> selectByExampleSelective(@Param("example") AllHycllxExample example, @Param("selective") AllHycllx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    List<AllHycllx> selectByExample(AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    AllHycllx selectByPrimaryKeySelective(@Param("hycllxbm") Integer hycllxbm, @Param("selective") AllHycllx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    AllHycllx selectByPrimaryKey(Integer hycllxbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllHycllx record, @Param("example") AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllHycllx record, @Param("example") AllHycllxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllHycllx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_hycllx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllHycllx record);
}