package com.yjh.db.dao;

import com.yjh.db.domain.AllSpkzsxz;
import com.yjh.db.domain.AllSpkzsxzExample;
import com.yjh.db.domain.AllSpkzsxzKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpkzsxzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    long countByExample(AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AllSpkzsxzKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int insert(AllSpkzsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int insertSelective(AllSpkzsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    AllSpkzsxz selectOneByExample(AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    AllSpkzsxz selectOneByExampleSelective(@Param("example") AllSpkzsxzExample example, @Param("selective") AllSpkzsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    List<AllSpkzsxz> selectByExampleSelective(@Param("example") AllSpkzsxzExample example, @Param("selective") AllSpkzsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    List<AllSpkzsxz> selectByExample(AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    AllSpkzsxz selectByPrimaryKeySelective(@Param("record") AllSpkzsxzKey key, @Param("selective") AllSpkzsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    AllSpkzsxz selectByPrimaryKey(AllSpkzsxzKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpkzsxz record, @Param("example") AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpkzsxz record, @Param("example") AllSpkzsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpkzsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkzsxz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpkzsxz record);
}