package com.yjh.db.dao;

import com.yjh.db.domain.AllSpssbk;
import com.yjh.db.domain.AllSpssbkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpssbkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    long countByExample(AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ssbkbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int insert(AllSpssbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int insertSelective(AllSpssbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    AllSpssbk selectOneByExample(AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    AllSpssbk selectOneByExampleSelective(@Param("example") AllSpssbkExample example, @Param("selective") AllSpssbk.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    List<AllSpssbk> selectByExampleSelective(@Param("example") AllSpssbkExample example, @Param("selective") AllSpssbk.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    List<AllSpssbk> selectByExample(AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    AllSpssbk selectByPrimaryKeySelective(@Param("ssbkbm") Integer ssbkbm, @Param("selective") AllSpssbk.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    AllSpssbk selectByPrimaryKey(Integer ssbkbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpssbk record, @Param("example") AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpssbk record, @Param("example") AllSpssbkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpssbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spssbk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpssbk record);
}