package com.yjh.db.dao;

import com.yjh.db.domain.AllSpjbxx;
import com.yjh.db.domain.AllSpjbxxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpjbxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    long countByExample(AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int insert(AllSpjbxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int insertSelective(AllSpjbxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    AllSpjbxx selectOneByExample(AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    AllSpjbxx selectOneByExampleSelective(@Param("example") AllSpjbxxExample example, @Param("selective") AllSpjbxx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    List<AllSpjbxx> selectByExampleSelective(@Param("example") AllSpjbxxExample example, @Param("selective") AllSpjbxx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    List<AllSpjbxx> selectByExample(AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    AllSpjbxx selectByPrimaryKeySelective(@Param("spbm") Integer spbm, @Param("selective") AllSpjbxx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    AllSpjbxx selectByPrimaryKey(Integer spbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpjbxx record, @Param("example") AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpjbxx record, @Param("example") AllSpjbxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpjbxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjbxx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpjbxx record);
}