package com.yjh.db.dao;

import com.yjh.db.domain.AllSplbkzsxExample;
import com.yjh.db.domain.AllSplbkzsxKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSplbkzsxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    long countByExample(AllSplbkzsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int deleteByExample(AllSplbkzsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AllSplbkzsxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int insert(AllSplbkzsxKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int insertSelective(AllSplbkzsxKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    AllSplbkzsxKey selectOneByExample(AllSplbkzsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    AllSplbkzsxKey selectOneByExampleSelective(@Param("example") AllSplbkzsxExample example, @Param("selective") AllSplbkzsxKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    List<AllSplbkzsxKey> selectByExampleSelective(@Param("example") AllSplbkzsxExample example, @Param("selective") AllSplbkzsxKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    List<AllSplbkzsxKey> selectByExample(AllSplbkzsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSplbkzsxKey record, @Param("example") AllSplbkzsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_splbkzsx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSplbkzsxKey record, @Param("example") AllSplbkzsxExample example);
}