package com.yjh.db.dao;

import com.yjh.db.domain.AllSpjggtp;
import com.yjh.db.domain.AllSpjggtpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpjggtpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    long countByExample(AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tpxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int insert(AllSpjggtp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int insertSelective(AllSpjggtp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    AllSpjggtp selectOneByExample(AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    AllSpjggtp selectOneByExampleSelective(@Param("example") AllSpjggtpExample example, @Param("selective") AllSpjggtp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    List<AllSpjggtp> selectByExampleSelective(@Param("example") AllSpjggtpExample example, @Param("selective") AllSpjggtp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    List<AllSpjggtp> selectByExample(AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    AllSpjggtp selectByPrimaryKeySelective(@Param("tpxh") Long tpxh, @Param("selective") AllSpjggtp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    AllSpjggtp selectByPrimaryKey(Long tpxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpjggtp record, @Param("example") AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpjggtp record, @Param("example") AllSpjggtpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpjggtp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjggtp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpjggtp record);
}