package com.yjh.db.dao;

import com.yjh.db.domain.AllSpkc;
import com.yjh.db.domain.AllSpkcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpkcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    long countByExample(AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spkcbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int insert(AllSpkc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int insertSelective(AllSpkc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    AllSpkc selectOneByExample(AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    AllSpkc selectOneByExampleSelective(@Param("example") AllSpkcExample example, @Param("selective") AllSpkc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    List<AllSpkc> selectByExampleSelective(@Param("example") AllSpkcExample example, @Param("selective") AllSpkc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    List<AllSpkc> selectByExample(AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    AllSpkc selectByPrimaryKeySelective(@Param("spkcbm") Integer spkcbm, @Param("selective") AllSpkc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    AllSpkc selectByPrimaryKey(Integer spkcbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpkc record, @Param("example") AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpkc record, @Param("example") AllSpkcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpkc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spkc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpkc record);
}