package com.yjh.db.dao;

import com.yjh.db.domain.AllSpjkctp;
import com.yjh.db.domain.AllSpjkctpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpjkctpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    long countByExample(AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tpxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int insert(AllSpjkctp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int insertSelective(AllSpjkctp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    AllSpjkctp selectOneByExample(AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    AllSpjkctp selectOneByExampleSelective(@Param("example") AllSpjkctpExample example, @Param("selective") AllSpjkctp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    List<AllSpjkctp> selectByExampleSelective(@Param("example") AllSpjkctpExample example, @Param("selective") AllSpjkctp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    List<AllSpjkctp> selectByExample(AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    AllSpjkctp selectByPrimaryKeySelective(@Param("tpxh") Long tpxh, @Param("selective") AllSpjkctp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    AllSpjkctp selectByPrimaryKey(Long tpxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpjkctp record, @Param("example") AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpjkctp record, @Param("example") AllSpjkctpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpjkctp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spjkctp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpjkctp record);
}