package com.yjh.db.dao;

import com.yjh.db.domain.AllSpggsxz;
import com.yjh.db.domain.AllSpggsxzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpggsxzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    long countByExample(AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spggsxzbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int insert(AllSpggsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int insertSelective(AllSpggsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    AllSpggsxz selectOneByExample(AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    AllSpggsxz selectOneByExampleSelective(@Param("example") AllSpggsxzExample example, @Param("selective") AllSpggsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    List<AllSpggsxz> selectByExampleSelective(@Param("example") AllSpggsxzExample example, @Param("selective") AllSpggsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    List<AllSpggsxz> selectByExample(AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    AllSpggsxz selectByPrimaryKeySelective(@Param("spggsxzbm") Integer spggsxzbm, @Param("selective") AllSpggsxz.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    AllSpggsxz selectByPrimaryKey(Integer spggsxzbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSpggsxz record, @Param("example") AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSpggsxz record, @Param("example") AllSpggsxzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSpggsxz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_spggsxz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSpggsxz record);
}