package com.yjh.db.dao;

import com.yjh.db.domain.AllSppp;
import com.yjh.db.domain.AllSpppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllSpppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    long countByExample(AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int deleteByExample(AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spppbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int insert(AllSppp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int insertSelective(AllSppp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    AllSppp selectOneByExample(AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    AllSppp selectOneByExampleSelective(@Param("example") AllSpppExample example, @Param("selective") AllSppp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    List<AllSppp> selectByExampleSelective(@Param("example") AllSpppExample example, @Param("selective") AllSppp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    List<AllSppp> selectByExample(AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    AllSppp selectByPrimaryKeySelective(@Param("spppbm") Integer spppbm, @Param("selective") AllSppp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    AllSppp selectByPrimaryKey(Integer spppbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSppp record, @Param("example") AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSppp record, @Param("example") AllSpppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSppp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_sppp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSppp record);
}