package com.yjh.db.dao;

import com.yjh.db.domain.AllYfgzgc;
import com.yjh.db.domain.AllYfgzgcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AllYfgzgcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    long countByExample(AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int deleteByExample(AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fygzbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int insert(AllYfgzgc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int insertSelective(AllYfgzgc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    AllYfgzgc selectOneByExample(AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    AllYfgzgc selectOneByExampleSelective(@Param("example") AllYfgzgcExample example, @Param("selective") AllYfgzgc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    List<AllYfgzgc> selectByExampleSelective(@Param("example") AllYfgzgcExample example, @Param("selective") AllYfgzgc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    List<AllYfgzgc> selectByExample(AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    AllYfgzgc selectByPrimaryKeySelective(@Param("fygzbm") Integer fygzbm, @Param("selective") AllYfgzgc.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    AllYfgzgc selectByPrimaryKey(Integer fygzbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllYfgzgc record, @Param("example") AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllYfgzgc record, @Param("example") AllYfgzgcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllYfgzgc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_yfgzgc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllYfgzgc record);
}