package com.yjh.db.dao;

import com.yjh.db.domain.HyCl;
import com.yjh.db.domain.HyClExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface HyClMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    long countByExample(HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int deleteByExample(HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long hyrzclbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int insert(HyCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int insertSelective(HyCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    HyCl selectOneByExample(HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    HyCl selectOneByExampleSelective(@Param("example") HyClExample example, @Param("selective") HyCl.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    List<HyCl> selectByExampleSelective(@Param("example") HyClExample example, @Param("selective") HyCl.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    List<HyCl> selectByExample(HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    HyCl selectByPrimaryKeySelective(@Param("hyrzclbm") Long hyrzclbm, @Param("selective") HyCl.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    HyCl selectByPrimaryKey(Long hyrzclbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HyCl record, @Param("example") HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HyCl record, @Param("example") HyClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HyCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_cl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HyCl record);
}