package com.yjh.db.dao;

import com.yjh.db.domain.SysJs;
import com.yjh.db.domain.SysJsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysJsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    long countByExample(SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int deleteByExample(SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jsbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int insert(SysJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int insertSelective(SysJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    SysJs selectOneByExample(SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    SysJs selectOneByExampleSelective(@Param("example") SysJsExample example, @Param("selective") SysJs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    List<SysJs> selectByExampleSelective(@Param("example") SysJsExample example, @Param("selective") SysJs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    List<SysJs> selectByExample(SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    SysJs selectByPrimaryKeySelective(@Param("jsbm") Integer jsbm, @Param("selective") SysJs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    SysJs selectByPrimaryKey(Integer jsbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysJs record, @Param("example") SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysJs record, @Param("example") SysJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_js
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysJs record);
}